 <font size="10">**Notebook 01: Anndata object generation**</font>
***

<div class="alert alert-info">
    
<b> <h1> ℹ️ <strong> <font size="6" color="black"> Important notebook information </font> </strong> </h1> </b>
    <hr>
    <font size="4" color="black">
        The purpose of this notebook is to generate <b>five</b> anndata objects which can then be used in other pre-processing notebooks later <br> <br>
    These anndata objects will hold raw count matrices in .X partition as they will store outputs from cellranger version 6-0-1 <br> <br>
    The following anndata objects will be made: </font> <br> 
    <ol> <font size="3" color="black">
        <li><b>F137</b> : Embryo_1 : Single Cell sequencing outputs and expression data available in the ArrayExpress database under accession number <a href="https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-11504/">E-MTAB-11504</a></li>
        <li><b>F147</b> : Embryo_2 : Single Cell sequencing outputs and expression data available in the ArrayExpress database under accession number <a href="https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-11520/">E-MTAB-11520</a></li>
        <li><b>F158</b> : Embryo_3 : Single Cell sequencing outputs and expression data available in the ArrayExpress database under accession number <a href="https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-11911/">E-MTAB-11911</a></li>
        <li><b>Combined_embryos</b> : Concatenated anndata object of F137, F147 and F158 with lanes</li>
        <li><b>Combined_embryos_suitable</b> : Combined_embryos anndata object with all lanes unsuitable for downstream analysis removed</li>
    </font> 
    </ol> 
    <font size="4" color="black">
    
<details> 
    <summary> <font size="4" color="black"> Lanes to be removed in combined anndata object </font> </summary> <br/>
    <font size="3" color="black"> Two lanes will be removed from the <b>Combined_embryos</b> anndata object due to reasons which are summarised in table below taken from Cellranger web outputs:<br> <br> </font> 
    <table style="margin-top:10px; margin-left:50px;">
        <tr>
            <th>Sample</th>
            <th>Lane to remove</th>
            <th>Spatial_location_replicate</th>
            <th>Reason</th>
        </tr>
        <tr>
            <td>F137</td>
            <td>WS_wEMB10202360</td>
            <td>Section_7_d</td>
            <td>Low Fraction Valid Barcodes 61.6% Ideal > 75%</td>
        </tr>
        <tr>
            <td>F147</td>
            <td>WS_wEMB11031943</td>
            <td>Section_5_c</td>
            <td>Low Number of Cells Detected 72 Ideal > 100</td>
        </tr>
    </table> <br>
    <font size="3" color="black"> The removal of these lanes will result in the generation of the <b>Combined_embryos_suitable</b> anndata object which is suitable for running downstream analysis in following scripts</font> 
</details>

<div class="alert alert-block alert-warning">
    
<b> <h1> ⚠️ <strong> <font size="6" color="black"> WARNING </font> </strong> ⚠️ </h1> </b>
    <hr>
<p style="color:black;">
    
<strong> <font size="4">  This notebook requires a large amount of memory to run as is from top to bottom. </font> </strong> <br> </p>
    <br>
<details> 
    <summary> <font size="4" color="black"> Memory amount </font> </summary> <br/>
    <font size="3" color="black">
        To run this notebook from top to bottom, the reading memory peaks at 175GB. <br> <br>
        Rough memory usage peaks running this notebook from top to bottom to make the individual anndata objects and save them one after another: <br>
        <ul type="disc">
            <li>Samples F137, F147 and F158: 80GB peak memory usage</li>
            <li>Combined all lanes: 161GB peak memory usage</li>
            <li>Combined with only suitable lanes: 175GB peak memory usage</li>
            </ul> <br>
        Note these peaks were monitored using Grafana not Jupyter lab memory bar which suggested the rough peak memory usage was around 160GB
    </font> 
</details>

<br>

<details> 
    <summary> <font size="4" color="black"> Resource availability </font> </summary> <br/>
    <font size="3" color="black">
        The resources used to run this notebook with high reading memory capabilities and monitor the memory usage using Grafana was provided by <a href="https://www.sanger.ac.uk/group/cellular-genetics-informatics/">Cellular Genetics Informatics</a>
    </font>
</details>

<br>
    
<details>
    <summary> <font size="4" color="black"> Options to decrease memory </font> </summary> <br/>
    <font size="3" color="black">
        It is possible to break this notebook up into separate parts which may help with memory consumption. <br> <br>
        Here is an example to try and reduce the required total amount of memory: <br>
        <ol>
            <li>Run this notebook until the first combined anndata object is saved (F137)</li>
            <li>Restart kernel and re-run script but skip over constructing and saving the first anndata object and instead construct and save the second anndata object (F147)</li>
            <li>Repeat step 2 but skip both the first and second anndata objects and proceed to construct and save the third anndata object (F158)</li>
            <li>Once all individual anndata objects are made for each sample (F137, F147 and F158), load in all anndata objects with corresponding names as variables and proceed to combine into one anndata object conatining all lanes and save</li> 
            <li>Restart kernal and load in only the combined anndata object with all lanes then subset out unsuitable lanes for downstream analysis and save</li>
        </ol>
    </font>
</details>

<br>
    
<details>
    <summary> <font size="4" color="black"> Alternative option to notebook 1 </font> </summary> <br/>
    <font size="3" color="black">
        Notebook 1 can be skipped if you wish to use provided resources which have already combined all lanes for each embryo already. <br> <br>
        These resources can be accessed <a href="https://www.website_link_here">here</a> but you will need to construct the anndata object yourself. <br> <br>
        This can be achieved using a premade function in scanpy package: <a href="https://scanpy.readthedocs.io/en/stable/generated/scanpy.read_10x_mtx.html?msclkid=e6c9fd53a84411ec8708898378d557dc">scanpy.read_10x_mtx</a> 
    </font>
</details>
</div>

***
# Import packages

In [ ]:
import numpy as np
import pandas as pd
import scanpy as sc
import os
import sys
import datetime

#to set unique date for outputs
calc_date = datetime.datetime.now()
date=calc_date.strftime('%Y-%m-%d')
#date=calc_date.strftime('%d-%m-%Y')
date = date.replace('-', '')

sc.settings.verbosity = 2

# Note: package versions can be located in dependencies at the bottom of the script

# User interaction block

In [ ]:
### User settings block ###

# Set root directory so all files and outputs can be found within one overarching location
root_directory = '/home/jovyan/mount_farm/nfs/ar32/Whole_embryo/'


# set directory path to Whole_Embryo_utils.py: This python script hold modules / functions which are used within the script 
Whole_Embryo_utils_path = root_directory + "Utlis/"


# set directory paths for each embryo cellranger outputs:
F137_path = root_directory + 'Cell_ranger_outs/F137/'
F147_path = root_directory + 'Cell_ranger_outs/F147/'
F158_path = root_directory + 'Cell_ranger_outs/F158/'


# set directory path to save anndata object outputs:
# Note if you put in a directory which does not exist you can request for the directory to be made if possible
Metadata_out_path = root_directory + 'Outputs/Metadata/Cell_numbers'
Objects_out_path = root_directory + 'Outputs/Objects/Raw_Objects/'


#############################################################################################################################


### Running checking directory paths to Whole_Embryo_utils.py and save directory paths ###

sys.path.append(Whole_Embryo_utils_path)
import Whole_Embryo_utils as eu

print('\033[1m' + 'Checking file path for saving anndata objects:' + '\033[0m', "\n")
eu.save_path(Objects_out_path)

Checking file path for saving anndata objects:

File path provided exists
To save data to this location use the inputed variable at the start of the file path

***
# Script start

## Generate anndata object of embryo: F137

In [ ]:
adata_list1 = []
print("="*100)
print("")
for i in list(range(36,81)):
    n = 'WS_wEMB102023'+str(i)
    print(f'Data to load: {n}')
    data = eu.load(F137_path + n + '/filtered_feature_bc_matrix/', Method='mtx')
    data.obs['sequencing_lane_ID'] = n
    adata_list1.append(data)
    print('\033[1m' + f'Data {n} loaded successfully. Data shape is {data.shape}' + '\033[0m', "\n")
    print("="*100,"\n")
    del data # to prevent stackoverflow

F137 = sc.AnnData.concatenate(*adata_list1, join = 'inner', batch_key = None, batch_categories = None, index_unique = None)
F137.obs.index = F137.obs.index.str.replace('-1','',regex=True)
F137.obs.index = F137.obs.index + '-' + F137.obs['sequencing_lane_ID']
F137.obs['haniffa_ID'] = 'F137'
F137.var['genome'] = 'GRCh38'
print("","\n",'\033[1m' + 'Embryo Sample F137 made successfully!' + '\033[0m',"\n")

====================================================================================================

Data to load: WS_wEMB10202336
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (2068, 36601)
Min count: 0.0
Max count: 4105.0

Data WS_wEMB10202336 loaded successfully. Data shape is (2068, 36601)

====================================================================================================

Data to load: WS_wEMB10202337
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (9303, 36601)
Min count: 0.0
Max count: 6596.0

Data WS_wEMB10202337 loaded successfully. Data shape is (9303, 36601)

====================================================================================================

Data to load: WS_wEMB10202338
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (9380, 36601)
Min count: 0.0
Max count: 11050.0

Data WS_wEMB10202338 loaded successfully. Data shape is (9380, 36601)

====================================================================================================

Data to load: WS_wEMB10202339
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (9223, 36601)
Min count: 0.0
Max count: 11112.0

Data WS_wEMB10202339 loaded successfully. Data shape is (9223, 36601)

====================================================================================================

Data to load: WS_wEMB10202340
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7515, 36601)
Min count: 0.0
Max count: 9168.0

Data WS_wEMB10202340 loaded successfully. Data shape is (7515, 36601)

====================================================================================================

Data to load: WS_wEMB10202341
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (9679, 36601)
Min count: 0.0
Max count: 6815.0

Data WS_wEMB10202341 loaded successfully. Data shape is (9679, 36601)

====================================================================================================

Data to load: WS_wEMB10202342
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (10539, 36601)
Min count: 0.0
Max count: 9870.0

Data WS_wEMB10202342 loaded successfully. Data shape is (10539, 36601)

====================================================================================================

Data to load: WS_wEMB10202343
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (9504, 36601)
Min count: 0.0
Max count: 7969.0

Data WS_wEMB10202343 loaded successfully. Data shape is (9504, 36601)

====================================================================================================

Data to load: WS_wEMB10202344
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (9489, 36601)
Min count: 0.0
Max count: 11586.0

Data WS_wEMB10202344 loaded successfully. Data shape is (9489, 36601)

====================================================================================================

Data to load: WS_wEMB10202345
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6809, 36601)
Min count: 0.0
Max count: 10343.0

Data WS_wEMB10202345 loaded successfully. Data shape is (6809, 36601)

====================================================================================================

Data to load: WS_wEMB10202346
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6498, 36601)
Min count: 0.0
Max count: 7930.0

Data WS_wEMB10202346 loaded successfully. Data shape is (6498, 36601)

====================================================================================================

Data to load: WS_wEMB10202347
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6866, 36601)
Min count: 0.0
Max count: 12017.0

Data WS_wEMB10202347 loaded successfully. Data shape is (6866, 36601)

====================================================================================================

Data to load: WS_wEMB10202348
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8410, 36601)
Min count: 0.0
Max count: 8488.0

Data WS_wEMB10202348 loaded successfully. Data shape is (8410, 36601)

====================================================================================================

Data to load: WS_wEMB10202349
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6688, 36601)
Min count: 0.0
Max count: 14864.0

Data WS_wEMB10202349 loaded successfully. Data shape is (6688, 36601)

====================================================================================================

Data to load: WS_wEMB10202350
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6349, 36601)
Min count: 0.0
Max count: 9221.0

Data WS_wEMB10202350 loaded successfully. Data shape is (6349, 36601)

====================================================================================================

Data to load: WS_wEMB10202351
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6563, 36601)
Min count: 0.0
Max count: 11140.0

Data WS_wEMB10202351 loaded successfully. Data shape is (6563, 36601)

====================================================================================================

Data to load: WS_wEMB10202352
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7549, 36601)
Min count: 0.0
Max count: 12389.0

Data WS_wEMB10202352 loaded successfully. Data shape is (7549, 36601)

====================================================================================================

Data to load: WS_wEMB10202353
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7314, 36601)
Min count: 0.0
Max count: 12190.0

Data WS_wEMB10202353 loaded successfully. Data shape is (7314, 36601)

====================================================================================================

Data to load: WS_wEMB10202354
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7376, 36601)
Min count: 0.0
Max count: 15940.0

Data WS_wEMB10202354 loaded successfully. Data shape is (7376, 36601)

====================================================================================================

Data to load: WS_wEMB10202355
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8433, 36601)
Min count: 0.0
Max count: 11842.0

Data WS_wEMB10202355 loaded successfully. Data shape is (8433, 36601)

====================================================================================================

Data to load: WS_wEMB10202356
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6559, 36601)
Min count: 0.0
Max count: 11348.0

Data WS_wEMB10202356 loaded successfully. Data shape is (6559, 36601)

====================================================================================================

Data to load: WS_wEMB10202357
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7380, 36601)
Min count: 0.0
Max count: 10602.0

Data WS_wEMB10202357 loaded successfully. Data shape is (7380, 36601)

====================================================================================================

Data to load: WS_wEMB10202358
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6899, 36601)
Min count: 0.0
Max count: 12083.0

Data WS_wEMB10202358 loaded successfully. Data shape is (6899, 36601)

====================================================================================================

Data to load: WS_wEMB10202359
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7029, 36601)
Min count: 0.0
Max count: 9173.0

Data WS_wEMB10202359 loaded successfully. Data shape is (7029, 36601)

====================================================================================================

Data to load: WS_wEMB10202360
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (16834, 36601)
Min count: 0.0
Max count: 7.0

Data WS_wEMB10202360 loaded successfully. Data shape is (16834, 36601)

====================================================================================================

Data to load: WS_wEMB10202361
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7021, 36601)
Min count: 0.0
Max count: 10307.0

Data WS_wEMB10202361 loaded successfully. Data shape is (7021, 36601)

====================================================================================================

Data to load: WS_wEMB10202362
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6748, 36601)
Min count: 0.0
Max count: 7965.0

Data WS_wEMB10202362 loaded successfully. Data shape is (6748, 36601)

====================================================================================================

Data to load: WS_wEMB10202363
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6614, 36601)
Min count: 0.0
Max count: 9788.0

Data WS_wEMB10202363 loaded successfully. Data shape is (6614, 36601)

====================================================================================================

Data to load: WS_wEMB10202364
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6666, 36601)
Min count: 0.0
Max count: 11529.0

Data WS_wEMB10202364 loaded successfully. Data shape is (6666, 36601)

====================================================================================================

Data to load: WS_wEMB10202365
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6943, 36601)
Min count: 0.0
Max count: 8235.0

Data WS_wEMB10202365 loaded successfully. Data shape is (6943, 36601)

====================================================================================================

Data to load: WS_wEMB10202366
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (5675, 36601)
Min count: 0.0
Max count: 9952.0

Data WS_wEMB10202366 loaded successfully. Data shape is (5675, 36601)

====================================================================================================

Data to load: WS_wEMB10202367
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (5838, 36601)
Min count: 0.0
Max count: 11432.0

Data WS_wEMB10202367 loaded successfully. Data shape is (5838, 36601)

====================================================================================================

Data to load: WS_wEMB10202368
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (5545, 36601)
Min count: 0.0
Max count: 13200.0

Data WS_wEMB10202368 loaded successfully. Data shape is (5545, 36601)

====================================================================================================

Data to load: WS_wEMB10202369
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6273, 36601)
Min count: 0.0
Max count: 7817.0

Data WS_wEMB10202369 loaded successfully. Data shape is (6273, 36601)

====================================================================================================

Data to load: WS_wEMB10202370
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6568, 36601)
Min count: 0.0
Max count: 10040.0

Data WS_wEMB10202370 loaded successfully. Data shape is (6568, 36601)

====================================================================================================

Data to load: WS_wEMB10202371
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6314, 36601)
Min count: 0.0
Max count: 8404.0

Data WS_wEMB10202371 loaded successfully. Data shape is (6314, 36601)

====================================================================================================

Data to load: WS_wEMB10202372
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6186, 36601)
Min count: 0.0
Max count: 10293.0

Data WS_wEMB10202372 loaded successfully. Data shape is (6186, 36601)

====================================================================================================

Data to load: WS_wEMB10202373
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6372, 36601)
Min count: 0.0
Max count: 11015.0

Data WS_wEMB10202373 loaded successfully. Data shape is (6372, 36601)

====================================================================================================

Data to load: WS_wEMB10202374
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7686, 36601)
Min count: 0.0
Max count: 10735.0

Data WS_wEMB10202374 loaded successfully. Data shape is (7686, 36601)

====================================================================================================

Data to load: WS_wEMB10202375
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (5978, 36601)
Min count: 0.0
Max count: 9820.0

Data WS_wEMB10202375 loaded successfully. Data shape is (5978, 36601)

====================================================================================================

Data to load: WS_wEMB10202376
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6280, 36601)
Min count: 0.0
Max count: 9816.0

Data WS_wEMB10202376 loaded successfully. Data shape is (6280, 36601)

====================================================================================================

Data to load: WS_wEMB10202377
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6702, 36601)
Min count: 0.0
Max count: 10583.0

Data WS_wEMB10202377 loaded successfully. Data shape is (6702, 36601)

====================================================================================================

Data to load: WS_wEMB10202378
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7510, 36601)
Min count: 0.0
Max count: 9876.0

Data WS_wEMB10202378 loaded successfully. Data shape is (7510, 36601)

====================================================================================================

Data to load: WS_wEMB10202379
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6866, 36601)
Min count: 0.0
Max count: 10062.0

Data WS_wEMB10202379 loaded successfully. Data shape is (6866, 36601)

====================================================================================================

Data to load: WS_wEMB10202380
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6751, 36601)
Min count: 0.0
Max count: 16057.0

Data WS_wEMB10202380 loaded successfully. Data shape is (6751, 36601)

====================================================================================================

Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.

 Embryo Sample F137 made successfully!

## Check anndata object

In [ ]:
data = F137
data_name = 'F137'

print('')
print('\033[1m' + f'{data_name}:'+ '\033[0m' ,data, "\n", "\n")
eu.describe_basic(data)
print('', "\n")
print('\033[1m' + f'{data_name}.obs :' + '\033[0m')
display(data.obs)
print('')
print('\033[1m' + f'{data_name}.var :' + '\033[0m')
display(data.var)

F137: AnnData object with n_obs × n_vars = 330792 × 36601
    obs: 'sequencing_lane_ID', 'haniffa_ID'
    var: 'gene_ids', 'feature_types', 'genome'


Overall shape: (330792, 36601)
Min count: 0.0
Max count: 16057.0


F137.obs :

                                 sequencing_lane_ID haniffa_ID
AAACCTGAGATCCGAG-WS_wEMB10202336    WS_wEMB10202336       F137
AAACCTGAGTACGATA-WS_wEMB10202336    WS_wEMB10202336       F137
AAACCTGCAGGTCCAC-WS_wEMB10202336    WS_wEMB10202336       F137
AAACCTGGTACCTACA-WS_wEMB10202336    WS_wEMB10202336       F137
AAACCTGGTATTCTCT-WS_wEMB10202336    WS_wEMB10202336       F137
...                                             ...        ...
TTTGTCAGTGACCAAG-WS_wEMB10202380    WS_wEMB10202380       F137
TTTGTCAGTTCCAACA-WS_wEMB10202380    WS_wEMB10202380       F137
TTTGTCATCAAACAAG-WS_wEMB10202380    WS_wEMB10202380       F137
TTTGTCATCCAATGGT-WS_wEMB10202380    WS_wEMB10202380       F137
TTTGTCATCTAGCACA-WS_wEMB10202380    WS_wEMB10202380       F137

[330792 rows x 2 columns]

F137.var :

                    gene_ids    feature_types  genome
MIR1302-2HG  ENSG00000243485  Gene Expression  GRCh38
FAM138A      ENSG00000237613  Gene Expression  GRCh38
OR4F5        ENSG00000186092  Gene Expression  GRCh38
AL627309.1   ENSG00000238009  Gene Expression  GRCh38
AL627309.3   ENSG00000239945  Gene Expression  GRCh38
...                      ...              ...     ...
AC141272.1   ENSG00000277836  Gene Expression  GRCh38
AC023491.2   ENSG00000278633  Gene Expression  GRCh38
AC007325.1   ENSG00000276017  Gene Expression  GRCh38
AC007325.4   ENSG00000278817  Gene Expression  GRCh38
AC007325.2   ENSG00000277196  Gene Expression  GRCh38

[36601 rows x 3 columns]

## Save anndata object: Sample F137
- Saving version of anndata object with all lanes for individual embryo
- This will have cellranger raw counts
- This will allow individual investigation of just sample F137 later without needing to load in any other biological sample

In [ ]:
F137.write_h5ad(Objects_out_path + 'F137_all_lanes_raw_counts_' + date + '.h5ad')

... storing 'sequencing_lane_ID' as categorical
... storing 'haniffa_ID' as categorical
... storing 'feature_types' as categorical
... storing 'genome' as categorical

## Generate anndata object of embryo: F147

In [ ]:
adata_list2 = []
print("="*100)
print("")
for i in list(range(19,67)):
    n = 'WS_wEMB110319'+str(i)
    print(f'Data to load: {n}')
    data = eu.load(F147_path + n + '/filtered_feature_bc_matrix/', Method='mtx')
    data.obs['sequencing_lane_ID'] = n
    adata_list2.append(data)
    print('\033[1m' + f'Data {n} loaded successfully. Data shape is {data.shape}' + '\033[0m', "\n")
    print("="*100,"\n")
    del data # to prevent stackoverflow

F147 = sc.AnnData.concatenate(*adata_list2, join = 'inner', batch_key = None, batch_categories = None, index_unique = None)
F147.obs.index = F147.obs.index.str.replace('-1','',regex=True)
F147.obs.index = F147.obs.index + '-' + F147.obs['sequencing_lane_ID']
F147.obs['haniffa_ID'] = 'F147'
F147.var['genome'] = 'GRCh38'
print("","\n",'\033[1m' + 'Embryo F147 made successfully!' + '\033[0m',"\n")

====================================================================================================

Data to load: WS_wEMB11031919
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (9471, 36601)
Min count: 0.0
Max count: 4213.0

Data WS_wEMB11031919 loaded successfully. Data shape is (9471, 36601)

====================================================================================================

Data to load: WS_wEMB11031920
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (13750, 36601)
Min count: 0.0
Max count: 4305.0

Data WS_wEMB11031920 loaded successfully. Data shape is (13750, 36601)

====================================================================================================

Data to load: WS_wEMB11031921
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (13259, 36601)
Min count: 0.0
Max count: 4848.0

Data WS_wEMB11031921 loaded successfully. Data shape is (13259, 36601)

====================================================================================================

Data to load: WS_wEMB11031922
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8357, 36601)
Min count: 0.0
Max count: 4004.0

Data WS_wEMB11031922 loaded successfully. Data shape is (8357, 36601)

====================================================================================================

Data to load: WS_wEMB11031923
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (4206, 36601)
Min count: 0.0
Max count: 3205.0

Data WS_wEMB11031923 loaded successfully. Data shape is (4206, 36601)

====================================================================================================

Data to load: WS_wEMB11031924
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (13282, 36601)
Min count: 0.0
Max count: 6253.0

Data WS_wEMB11031924 loaded successfully. Data shape is (13282, 36601)

====================================================================================================

Data to load: WS_wEMB11031925
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (12793, 36601)
Min count: 0.0
Max count: 5914.0

Data WS_wEMB11031925 loaded successfully. Data shape is (12793, 36601)

====================================================================================================

Data to load: WS_wEMB11031926
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (10891, 36601)
Min count: 0.0
Max count: 7740.0

Data WS_wEMB11031926 loaded successfully. Data shape is (10891, 36601)

====================================================================================================

Data to load: WS_wEMB11031927
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (11651, 36601)
Min count: 0.0
Max count: 10589.0

Data WS_wEMB11031927 loaded successfully. Data shape is (11651, 36601)

====================================================================================================

Data to load: WS_wEMB11031928
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (12849, 36601)
Min count: 0.0
Max count: 7513.0

Data WS_wEMB11031928 loaded successfully. Data shape is (12849, 36601)

====================================================================================================

Data to load: WS_wEMB11031929
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (10679, 36601)
Min count: 0.0
Max count: 7480.0

Data WS_wEMB11031929 loaded successfully. Data shape is (10679, 36601)

====================================================================================================

Data to load: WS_wEMB11031930
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8753, 36601)
Min count: 0.0
Max count: 10378.0

Data WS_wEMB11031930 loaded successfully. Data shape is (8753, 36601)

====================================================================================================

Data to load: WS_wEMB11031931
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8848, 36601)
Min count: 0.0
Max count: 6955.0

Data WS_wEMB11031931 loaded successfully. Data shape is (8848, 36601)

====================================================================================================

Data to load: WS_wEMB11031932
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (13763, 36601)
Min count: 0.0
Max count: 9863.0

Data WS_wEMB11031932 loaded successfully. Data shape is (13763, 36601)

====================================================================================================

Data to load: WS_wEMB11031933
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (9605, 36601)
Min count: 0.0
Max count: 7760.0

Data WS_wEMB11031933 loaded successfully. Data shape is (9605, 36601)

====================================================================================================

Data to load: WS_wEMB11031934
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (9007, 36601)
Min count: 0.0
Max count: 7398.0

Data WS_wEMB11031934 loaded successfully. Data shape is (9007, 36601)

====================================================================================================

Data to load: WS_wEMB11031935
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (5599, 36601)
Min count: 0.0
Max count: 6998.0

Data WS_wEMB11031935 loaded successfully. Data shape is (5599, 36601)

====================================================================================================

Data to load: WS_wEMB11031936
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7079, 36601)
Min count: 0.0
Max count: 5401.0

Data WS_wEMB11031936 loaded successfully. Data shape is (7079, 36601)

====================================================================================================

Data to load: WS_wEMB11031937
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8254, 36601)
Min count: 0.0
Max count: 9225.0

Data WS_wEMB11031937 loaded successfully. Data shape is (8254, 36601)

====================================================================================================

Data to load: WS_wEMB11031938
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (11872, 36601)
Min count: 0.0
Max count: 8558.0

Data WS_wEMB11031938 loaded successfully. Data shape is (11872, 36601)

====================================================================================================

Data to load: WS_wEMB11031939
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (10946, 36601)
Min count: 0.0
Max count: 8726.0

Data WS_wEMB11031939 loaded successfully. Data shape is (10946, 36601)

====================================================================================================

Data to load: WS_wEMB11031940
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7628, 36601)
Min count: 0.0
Max count: 9200.0

Data WS_wEMB11031940 loaded successfully. Data shape is (7628, 36601)

====================================================================================================

Data to load: WS_wEMB11031941
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7440, 36601)
Min count: 0.0
Max count: 5713.0

Data WS_wEMB11031941 loaded successfully. Data shape is (7440, 36601)

====================================================================================================

Data to load: WS_wEMB11031942
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (11663, 36601)
Min count: 0.0
Max count: 5219.0

Data WS_wEMB11031942 loaded successfully. Data shape is (11663, 36601)

====================================================================================================

Data to load: WS_wEMB11031943
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (72, 36601)
Min count: 0.0
Max count: 1114.0

Data WS_wEMB11031943 loaded successfully. Data shape is (72, 36601)

====================================================================================================

Data to load: WS_wEMB11031944
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8322, 36601)
Min count: 0.0
Max count: 6689.0

Data WS_wEMB11031944 loaded successfully. Data shape is (8322, 36601)

====================================================================================================

Data to load: WS_wEMB11031945
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7541, 36601)
Min count: 0.0
Max count: 4572.0

Data WS_wEMB11031945 loaded successfully. Data shape is (7541, 36601)

====================================================================================================

Data to load: WS_wEMB11031946
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (12953, 36601)
Min count: 0.0
Max count: 4259.0

Data WS_wEMB11031946 loaded successfully. Data shape is (12953, 36601)

====================================================================================================

Data to load: WS_wEMB11031947
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7800, 36601)
Min count: 0.0
Max count: 8737.0

Data WS_wEMB11031947 loaded successfully. Data shape is (7800, 36601)

====================================================================================================

Data to load: WS_wEMB11031948
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7515, 36601)
Min count: 0.0
Max count: 4683.0

Data WS_wEMB11031948 loaded successfully. Data shape is (7515, 36601)

====================================================================================================

Data to load: WS_wEMB11031949
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8473, 36601)
Min count: 0.0
Max count: 3408.0

Data WS_wEMB11031949 loaded successfully. Data shape is (8473, 36601)

====================================================================================================

Data to load: WS_wEMB11031950
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (19507, 36601)
Min count: 0.0
Max count: 2633.0

Data WS_wEMB11031950 loaded successfully. Data shape is (19507, 36601)

====================================================================================================

Data to load: WS_wEMB11031951
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (14126, 36601)
Min count: 0.0
Max count: 11914.0

Data WS_wEMB11031951 loaded successfully. Data shape is (14126, 36601)

====================================================================================================

Data to load: WS_wEMB11031952
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7765, 36601)
Min count: 0.0
Max count: 8629.0

Data WS_wEMB11031952 loaded successfully. Data shape is (7765, 36601)

====================================================================================================

Data to load: WS_wEMB11031953
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (11105, 36601)
Min count: 0.0
Max count: 11254.0

Data WS_wEMB11031953 loaded successfully. Data shape is (11105, 36601)

====================================================================================================

Data to load: WS_wEMB11031954
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7171, 36601)
Min count: 0.0
Max count: 3943.0

Data WS_wEMB11031954 loaded successfully. Data shape is (7171, 36601)

====================================================================================================

Data to load: WS_wEMB11031955
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (11750, 36601)
Min count: 0.0
Max count: 8342.0

Data WS_wEMB11031955 loaded successfully. Data shape is (11750, 36601)

====================================================================================================

Data to load: WS_wEMB11031956
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (14029, 36601)
Min count: 0.0
Max count: 7861.0

Data WS_wEMB11031956 loaded successfully. Data shape is (14029, 36601)

====================================================================================================

Data to load: WS_wEMB11031957
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (10631, 36601)
Min count: 0.0
Max count: 12734.0

Data WS_wEMB11031957 loaded successfully. Data shape is (10631, 36601)

====================================================================================================

Data to load: WS_wEMB11031958
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (9751, 36601)
Min count: 0.0
Max count: 9344.0

Data WS_wEMB11031958 loaded successfully. Data shape is (9751, 36601)

====================================================================================================

Data to load: WS_wEMB11031959
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7663, 36601)
Min count: 0.0
Max count: 5889.0

Data WS_wEMB11031959 loaded successfully. Data shape is (7663, 36601)

====================================================================================================

Data to load: WS_wEMB11031960
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6810, 36601)
Min count: 0.0
Max count: 6118.0

Data WS_wEMB11031960 loaded successfully. Data shape is (6810, 36601)

====================================================================================================

Data to load: WS_wEMB11031961
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8893, 36601)
Min count: 0.0
Max count: 6786.0

Data WS_wEMB11031961 loaded successfully. Data shape is (8893, 36601)

====================================================================================================

Data to load: WS_wEMB11031962
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6543, 36601)
Min count: 0.0
Max count: 5291.0

Data WS_wEMB11031962 loaded successfully. Data shape is (6543, 36601)

====================================================================================================

Data to load: WS_wEMB11031963
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7300, 36601)
Min count: 0.0
Max count: 6131.0

Data WS_wEMB11031963 loaded successfully. Data shape is (7300, 36601)

====================================================================================================

Data to load: WS_wEMB11031964
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8125, 36601)
Min count: 0.0
Max count: 8629.0

Data WS_wEMB11031964 loaded successfully. Data shape is (8125, 36601)

====================================================================================================

Data to load: WS_wEMB11031965
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8660, 36601)
Min count: 0.0
Max count: 6224.0

Data WS_wEMB11031965 loaded successfully. Data shape is (8660, 36601)

====================================================================================================

Data to load: WS_wEMB11031966
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8526, 36601)
Min count: 0.0
Max count: 6617.0

Data WS_wEMB11031966 loaded successfully. Data shape is (8526, 36601)

====================================================================================================

Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.

 Embryo F147 made successfully!

## Check anndata object

In [ ]:
data = F147
data_name = 'F147'

print('')
print('\033[1m' + f'{data_name}:'+ '\033[0m' ,data, "\n", "\n")
eu.describe_basic(data)
print('', "\n")
print('\033[1m' + f'{data_name}.obs :' + '\033[0m')
display(data.obs)
print('')
print('\033[1m' + f'{data_name}.var :' + '\033[0m')
display(data.var)

F147: AnnData object with n_obs × n_vars = 462676 × 36601
    obs: 'sequencing_lane_ID', 'haniffa_ID'
    var: 'gene_ids', 'feature_types', 'genome'


Overall shape: (462676, 36601)
Min count: 0.0
Max count: 12734.0


F147.obs :

                                 sequencing_lane_ID haniffa_ID
AAACCTGAGCCAGGAT-WS_wEMB11031919    WS_wEMB11031919       F147
AAACCTGAGGACCACA-WS_wEMB11031919    WS_wEMB11031919       F147
AAACCTGAGGCGACAT-WS_wEMB11031919    WS_wEMB11031919       F147
AAACCTGAGGGATACC-WS_wEMB11031919    WS_wEMB11031919       F147
AAACCTGAGTATGACA-WS_wEMB11031919    WS_wEMB11031919       F147
...                                             ...        ...
TTTGTCATCATTTGGG-WS_wEMB11031966    WS_wEMB11031966       F147
TTTGTCATCCAGTAGT-WS_wEMB11031966    WS_wEMB11031966       F147
TTTGTCATCCCGACTT-WS_wEMB11031966    WS_wEMB11031966       F147
TTTGTCATCCGGGTGT-WS_wEMB11031966    WS_wEMB11031966       F147
TTTGTCATCTCCCTGA-WS_wEMB11031966    WS_wEMB11031966       F147

[462676 rows x 2 columns]

F147.var :

                    gene_ids    feature_types  genome
MIR1302-2HG  ENSG00000243485  Gene Expression  GRCh38
FAM138A      ENSG00000237613  Gene Expression  GRCh38
OR4F5        ENSG00000186092  Gene Expression  GRCh38
AL627309.1   ENSG00000238009  Gene Expression  GRCh38
AL627309.3   ENSG00000239945  Gene Expression  GRCh38
...                      ...              ...     ...
AC141272.1   ENSG00000277836  Gene Expression  GRCh38
AC023491.2   ENSG00000278633  Gene Expression  GRCh38
AC007325.1   ENSG00000276017  Gene Expression  GRCh38
AC007325.4   ENSG00000278817  Gene Expression  GRCh38
AC007325.2   ENSG00000277196  Gene Expression  GRCh38

[36601 rows x 3 columns]

## Save anndata object: Sample F147
- Saving version of anndata object with all lanes for individual embryo
- This will have cellranger raw counts
- This will allow individual investigation of just sample F137 later without needing to load in any other biological sample

In [ ]:
F147.write_h5ad(Objects_out_path + 'F147_all_lanes_raw_counts_' + date + '.h5ad')

... storing 'sequencing_lane_ID' as categorical
... storing 'haniffa_ID' as categorical
... storing 'feature_types' as categorical
... storing 'genome' as categorical

## Generate anndata object of embryo: F158

In [ ]:
adata_list3 = []
print("="*100)
print("")
for i in list(range(5,56)):
    if i < 10:   # To account for single digit numbers
        i = '0'+str(i)
    if i in list(range(32,35)):    # to account for gap in numbering in lanes
        continue
    n = 'WS_wEMB121421'+str(i)
    print(f'Data to load: {n}')
    data = eu.load(F158_path + n + '/filtered_feature_bc_matrix/', Method='mtx')
    data.obs['sequencing_lane_ID'] = n
    adata_list3.append(data)
    print('\033[1m' + f'Data {n} loaded successfully. Data shape is {data.shape}' + '\033[0m', "\n")
    print("="*100,"\n")
    del data # to prevent stackoverflow

F158 = sc.AnnData.concatenate(*adata_list3, join = 'inner', batch_key = None, batch_categories = None, index_unique = None)
F158.obs.index = F158.obs.index.str.replace('-1','',regex=True)
F158.obs.index = F158.obs.index + '-' + F158.obs['sequencing_lane_ID']
F158.obs['haniffa_ID'] = 'F158'
F158.var['genome'] = 'GRCh38'
print("","\n",'\033[1m' + 'Embryo F158 made successfully!' + '\033[0m',"\n")

====================================================================================================

Data to load: WS_wEMB12142105
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (10357, 36601)
Min count: 0.0
Max count: 12414.0

Data WS_wEMB12142105 loaded successfully. Data shape is (10357, 36601)

====================================================================================================

Data to load: WS_wEMB12142106
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (10456, 36601)
Min count: 0.0
Max count: 6666.0

Data WS_wEMB12142106 loaded successfully. Data shape is (10456, 36601)

====================================================================================================

Data to load: WS_wEMB12142107
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (9114, 36601)
Min count: 0.0
Max count: 15643.0

Data WS_wEMB12142107 loaded successfully. Data shape is (9114, 36601)

====================================================================================================

Data to load: WS_wEMB12142108
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7090, 36601)
Min count: 0.0
Max count: 11450.0

Data WS_wEMB12142108 loaded successfully. Data shape is (7090, 36601)

====================================================================================================

Data to load: WS_wEMB12142109
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8353, 36601)
Min count: 0.0
Max count: 4892.0

Data WS_wEMB12142109 loaded successfully. Data shape is (8353, 36601)

====================================================================================================

Data to load: WS_wEMB12142110
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (11418, 36601)
Min count: 0.0
Max count: 6334.0

Data WS_wEMB12142110 loaded successfully. Data shape is (11418, 36601)

====================================================================================================

Data to load: WS_wEMB12142111
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7906, 36601)
Min count: 0.0
Max count: 8885.0

Data WS_wEMB12142111 loaded successfully. Data shape is (7906, 36601)

====================================================================================================

Data to load: WS_wEMB12142112
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7465, 36601)
Min count: 0.0
Max count: 8103.0

Data WS_wEMB12142112 loaded successfully. Data shape is (7465, 36601)

====================================================================================================

Data to load: WS_wEMB12142113
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8469, 36601)
Min count: 0.0
Max count: 5425.0

Data WS_wEMB12142113 loaded successfully. Data shape is (8469, 36601)

====================================================================================================

Data to load: WS_wEMB12142114
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (10648, 36601)
Min count: 0.0
Max count: 5789.0

Data WS_wEMB12142114 loaded successfully. Data shape is (10648, 36601)

====================================================================================================

Data to load: WS_wEMB12142115
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7249, 36601)
Min count: 0.0
Max count: 7159.0

Data WS_wEMB12142115 loaded successfully. Data shape is (7249, 36601)

====================================================================================================

Data to load: WS_wEMB12142116
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7019, 36601)
Min count: 0.0
Max count: 7908.0

Data WS_wEMB12142116 loaded successfully. Data shape is (7019, 36601)

====================================================================================================

Data to load: WS_wEMB12142117
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (9226, 36601)
Min count: 0.0
Max count: 5288.0

Data WS_wEMB12142117 loaded successfully. Data shape is (9226, 36601)

====================================================================================================

Data to load: WS_wEMB12142118
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (9654, 36601)
Min count: 0.0
Max count: 4755.0

Data WS_wEMB12142118 loaded successfully. Data shape is (9654, 36601)

====================================================================================================

Data to load: WS_wEMB12142119
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7283, 36601)
Min count: 0.0
Max count: 8647.0

Data WS_wEMB12142119 loaded successfully. Data shape is (7283, 36601)

====================================================================================================

Data to load: WS_wEMB12142120
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8781, 36601)
Min count: 0.0
Max count: 12823.0

Data WS_wEMB12142120 loaded successfully. Data shape is (8781, 36601)

====================================================================================================

Data to load: WS_wEMB12142121
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (9796, 36601)
Min count: 0.0
Max count: 3532.0

Data WS_wEMB12142121 loaded successfully. Data shape is (9796, 36601)

====================================================================================================

Data to load: WS_wEMB12142122
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (9023, 36601)
Min count: 0.0
Max count: 3466.0

Data WS_wEMB12142122 loaded successfully. Data shape is (9023, 36601)

====================================================================================================

Data to load: WS_wEMB12142123
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7411, 36601)
Min count: 0.0
Max count: 2710.0

Data WS_wEMB12142123 loaded successfully. Data shape is (7411, 36601)

====================================================================================================

Data to load: WS_wEMB12142124
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6431, 36601)
Min count: 0.0
Max count: 11884.0

Data WS_wEMB12142124 loaded successfully. Data shape is (6431, 36601)

====================================================================================================

Data to load: WS_wEMB12142125
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8058, 36601)
Min count: 0.0
Max count: 9748.0

Data WS_wEMB12142125 loaded successfully. Data shape is (8058, 36601)

====================================================================================================

Data to load: WS_wEMB12142126
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8944, 36601)
Min count: 0.0
Max count: 9485.0

Data WS_wEMB12142126 loaded successfully. Data shape is (8944, 36601)

====================================================================================================

Data to load: WS_wEMB12142127
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7610, 36601)
Min count: 0.0
Max count: 3046.0

Data WS_wEMB12142127 loaded successfully. Data shape is (7610, 36601)

====================================================================================================

Data to load: WS_wEMB12142128
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (6584, 36601)
Min count: 0.0
Max count: 2498.0

Data WS_wEMB12142128 loaded successfully. Data shape is (6584, 36601)

====================================================================================================

Data to load: WS_wEMB12142129
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (9669, 36601)
Min count: 0.0
Max count: 5380.0

Data WS_wEMB12142129 loaded successfully. Data shape is (9669, 36601)

====================================================================================================

Data to load: WS_wEMB12142130
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8618, 36601)
Min count: 0.0
Max count: 4948.0

Data WS_wEMB12142130 loaded successfully. Data shape is (8618, 36601)

====================================================================================================

Data to load: WS_wEMB12142131
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7566, 36601)
Min count: 0.0
Max count: 989.0

Data WS_wEMB12142131 loaded successfully. Data shape is (7566, 36601)

====================================================================================================

Data to load: WS_wEMB12142135
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8332, 36601)
Min count: 0.0
Max count: 6763.0

Data WS_wEMB12142135 loaded successfully. Data shape is (8332, 36601)

====================================================================================================

Data to load: WS_wEMB12142136
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (9830, 36601)
Min count: 0.0
Max count: 7271.0

Data WS_wEMB12142136 loaded successfully. Data shape is (9830, 36601)

====================================================================================================

Data to load: WS_wEMB12142137
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8461, 36601)
Min count: 0.0
Max count: 7359.0

Data WS_wEMB12142137 loaded successfully. Data shape is (8461, 36601)

====================================================================================================

Data to load: WS_wEMB12142138
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8443, 36601)
Min count: 0.0
Max count: 7564.0

Data WS_wEMB12142138 loaded successfully. Data shape is (8443, 36601)

====================================================================================================

Data to load: WS_wEMB12142139
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7826, 36601)
Min count: 0.0
Max count: 6667.0

Data WS_wEMB12142139 loaded successfully. Data shape is (7826, 36601)

====================================================================================================

Data to load: WS_wEMB12142140
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8250, 36601)
Min count: 0.0
Max count: 4484.0

Data WS_wEMB12142140 loaded successfully. Data shape is (8250, 36601)

====================================================================================================

Data to load: WS_wEMB12142141
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8769, 36601)
Min count: 0.0
Max count: 8053.0

Data WS_wEMB12142141 loaded successfully. Data shape is (8769, 36601)

====================================================================================================

Data to load: WS_wEMB12142142
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (4197, 36601)
Min count: 0.0
Max count: 7762.0

Data WS_wEMB12142142 loaded successfully. Data shape is (4197, 36601)

====================================================================================================

Data to load: WS_wEMB12142143
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8315, 36601)
Min count: 0.0
Max count: 6546.0

Data WS_wEMB12142143 loaded successfully. Data shape is (8315, 36601)

====================================================================================================

Data to load: WS_wEMB12142144
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7851, 36601)
Min count: 0.0
Max count: 6081.0

Data WS_wEMB12142144 loaded successfully. Data shape is (7851, 36601)

====================================================================================================

Data to load: WS_wEMB12142145
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7807, 36601)
Min count: 0.0
Max count: 8134.0

Data WS_wEMB12142145 loaded successfully. Data shape is (7807, 36601)

====================================================================================================

Data to load: WS_wEMB12142146
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8674, 36601)
Min count: 0.0
Max count: 6915.0

Data WS_wEMB12142146 loaded successfully. Data shape is (8674, 36601)

====================================================================================================

Data to load: WS_wEMB12142147
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (10439, 36601)
Min count: 0.0
Max count: 7465.0

Data WS_wEMB12142147 loaded successfully. Data shape is (10439, 36601)

====================================================================================================

Data to load: WS_wEMB12142148
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (11565, 36601)
Min count: 0.0
Max count: 4766.0

Data WS_wEMB12142148 loaded successfully. Data shape is (11565, 36601)

====================================================================================================

Data to load: WS_wEMB12142149
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8276, 36601)
Min count: 0.0
Max count: 6588.0

Data WS_wEMB12142149 loaded successfully. Data shape is (8276, 36601)

====================================================================================================

Data to load: WS_wEMB12142150
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8083, 36601)
Min count: 0.0
Max count: 6904.0

Data WS_wEMB12142150 loaded successfully. Data shape is (8083, 36601)

====================================================================================================

Data to load: WS_wEMB12142151
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (8891, 36601)
Min count: 0.0
Max count: 5199.0

Data WS_wEMB12142151 loaded successfully. Data shape is (8891, 36601)

====================================================================================================

Data to load: WS_wEMB12142152
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7492, 36601)
Min count: 0.0
Max count: 2369.0

Data WS_wEMB12142152 loaded successfully. Data shape is (7492, 36601)

====================================================================================================

Data to load: WS_wEMB12142153
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7615, 36601)
Min count: 0.0
Max count: 6869.0

Data WS_wEMB12142153 loaded successfully. Data shape is (7615, 36601)

====================================================================================================

Data to load: WS_wEMB12142154
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (7803, 36601)
Min count: 0.0
Max count: 6901.0

Data WS_wEMB12142154 loaded successfully. Data shape is (7803, 36601)

====================================================================================================

Data to load: WS_wEMB12142155
Beginning to load data:
Method chosen for loading is mtx out of the options: h5ad , h5 or mtx

Data loaded in successfully
Overall shape: (9402, 36601)
Min count: 0.0
Max count: 6203.0

Data WS_wEMB12142155 loaded successfully. Data shape is (9402, 36601)

====================================================================================================

Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.

 Embryo F147 made successfully!

## Check anndata object

In [ ]:
data = F158
data_name = 'F158'

print('')
print('\033[1m' + f'{data_name}:'+ '\033[0m' ,data, "\n", "\n")
eu.describe_basic(data)
print('', "\n")
print('\033[1m' + f'{data_name}.obs :' + '\033[0m')
display(data.obs)
print('')
print('\033[1m' + f'{data_name}.var :' + '\033[0m')
display(data.var)

F158: AnnData object with n_obs × n_vars = 406519 × 36601
    obs: 'sequencing_lane_ID', 'haniffa_ID'
    var: 'gene_ids', 'feature_types', 'genome'


Overall shape: (406519, 36601)
Min count: 0.0
Max count: 15643.0


F158.obs :

                                 sequencing_lane_ID haniffa_ID
AAACCTGAGACCCACC-WS_wEMB12142105    WS_wEMB12142105       F158
AAACCTGAGATATACG-WS_wEMB12142105    WS_wEMB12142105       F158
AAACCTGAGCTAACAA-WS_wEMB12142105    WS_wEMB12142105       F158
AAACCTGAGGCGCTCT-WS_wEMB12142105    WS_wEMB12142105       F158
AAACCTGAGGGCTTGA-WS_wEMB12142105    WS_wEMB12142105       F158
...                                             ...        ...
TTTGTCATCAGCATGT-WS_wEMB12142155    WS_wEMB12142155       F158
TTTGTCATCAGTCCCT-WS_wEMB12142155    WS_wEMB12142155       F158
TTTGTCATCCCTTGCA-WS_wEMB12142155    WS_wEMB12142155       F158
TTTGTCATCCTCATTA-WS_wEMB12142155    WS_wEMB12142155       F158
TTTGTCATCCTTCAAT-WS_wEMB12142155    WS_wEMB12142155       F158

[406519 rows x 2 columns]

F158.var :

                    gene_ids    feature_types  genome
MIR1302-2HG  ENSG00000243485  Gene Expression  GRCh38
FAM138A      ENSG00000237613  Gene Expression  GRCh38
OR4F5        ENSG00000186092  Gene Expression  GRCh38
AL627309.1   ENSG00000238009  Gene Expression  GRCh38
AL627309.3   ENSG00000239945  Gene Expression  GRCh38
...                      ...              ...     ...
AC141272.1   ENSG00000277836  Gene Expression  GRCh38
AC023491.2   ENSG00000278633  Gene Expression  GRCh38
AC007325.1   ENSG00000276017  Gene Expression  GRCh38
AC007325.4   ENSG00000278817  Gene Expression  GRCh38
AC007325.2   ENSG00000277196  Gene Expression  GRCh38

[36601 rows x 3 columns]

## Save anndata object: Sample F158
- Saving version of anndata object with all lanes for individual embryo
- This will have cellranger raw counts
- This will allow individual investigation of just sample F137 later without needing to load in any other biological sample

In [ ]:
F158.write_h5ad(Objects_out_path + 'F158_all_lanes_raw_counts_' + date + '.h5ad')

... storing 'sequencing_lane_ID' as categorical
... storing 'haniffa_ID' as categorical
... storing 'feature_types' as categorical
... storing 'genome' as categorical

# Concatenate all samples together
- Will create a combined anndata object of all 3 embryos into 1 anndata object
- This will have cellranger raw counts
- Save anndata object so have 1 object with all embryos within with no lanes filtered out

In [ ]:
adata_list_all = [F137,F147,F158] 
Combined_embryos = sc.AnnData.concatenate(*adata_list_all, join='inner', batch_key = None, batch_categories = None, index_unique = None)
Combined_embryos.write_h5ad(Objects_out_path + 'Combined_Embryos_all_lanes_raw_counts_' + date + '.h5ad')

... storing 'sequencing_lane_ID' as categorical
... storing 'haniffa_ID' as categorical

## Remove lanes unsuitable for downstream analysis
- Reasonings for lane removal provided above in script

In [ ]:
# Make list of lanes to remove from combined 
Lanes_to_remove = [
# Embryo1
'WS_wEMB10202360',
# Embryo2
'WS_wEMB11031943'
]

len_cells_before_removal = len(Combined_embryos.obs)
Combined_embryos_suitable = Combined_embryos[~Combined_embryos.obs['sequencing_lane_ID'].isin(Lanes_to_remove),:][:]
len_cells_after_removal = len(Combined_embryos_suitable.obs)
print(f'Number of cells removed by removing unsuitable lanes: {len_cells_before_removal-len_cells_after_removal}', '\n')

data = Combined_embryos_suitable
data_name = 'Combined_embryos_suitable'

print('\033[1m' + f'Final summary of {data_name} anndata object:' + '\033[0m')
eu.describe_basic(data)
print('', "\n")
print('\033[1m' + f'{data_name}.obs :' + '\033[0m')
display(data.obs)
print('')
print('\033[1m' + f'{data_name}.var :' + '\033[0m')
display(data.var)

Number of cells removed by removing unsuitable lanes: 16906

Final summary of Combined_embryos_suitable anndata object:
Overall shape: (1183081, 36601)
Min count: 0.0
Max count: 16057.0


Combined_embryos_suitable.obs :

                                 sequencing_lane_ID haniffa_ID
AAACCTGAGATCCGAG-WS_wEMB10202336    WS_wEMB10202336       F137
AAACCTGAGTACGATA-WS_wEMB10202336    WS_wEMB10202336       F137
AAACCTGCAGGTCCAC-WS_wEMB10202336    WS_wEMB10202336       F137
AAACCTGGTACCTACA-WS_wEMB10202336    WS_wEMB10202336       F137
AAACCTGGTATTCTCT-WS_wEMB10202336    WS_wEMB10202336       F137
...                                             ...        ...
TTTGTCATCAGCATGT-WS_wEMB12142155    WS_wEMB12142155       F158
TTTGTCATCAGTCCCT-WS_wEMB12142155    WS_wEMB12142155       F158
TTTGTCATCCCTTGCA-WS_wEMB12142155    WS_wEMB12142155       F158
TTTGTCATCCTCATTA-WS_wEMB12142155    WS_wEMB12142155       F158
TTTGTCATCCTTCAAT-WS_wEMB12142155    WS_wEMB12142155       F158

[1183081 rows x 2 columns]

Combined_embryos_suitable.var :

                    gene_ids    feature_types  genome
MIR1302-2HG  ENSG00000243485  Gene Expression  GRCh38
FAM138A      ENSG00000237613  Gene Expression  GRCh38
OR4F5        ENSG00000186092  Gene Expression  GRCh38
AL627309.1   ENSG00000238009  Gene Expression  GRCh38
AL627309.3   ENSG00000239945  Gene Expression  GRCh38
...                      ...              ...     ...
AC141272.1   ENSG00000277836  Gene Expression  GRCh38
AC023491.2   ENSG00000278633  Gene Expression  GRCh38
AC007325.1   ENSG00000276017  Gene Expression  GRCh38
AC007325.4   ENSG00000278817  Gene Expression  GRCh38
AC007325.2   ENSG00000277196  Gene Expression  GRCh38

[36601 rows x 3 columns]

# Review metadata
- This will only be done for the Combined_embryos_suitable anndata object as this is the object which will be used for downstream analysis as only contains suitable lanes of interest

In [ ]:
pd.set_option('display.max_rows', 150)
pd.set_option('display.max_columns', 150)

print('\033[1m' +"Column dtypes:"+ '\033[0m')
display(Combined_embryos_suitable.obs.info())
print("","\n")
print('\033[1m' +"Number of cells grouped by: embryo -> sequencing lane:"+ '\033[0m')
display(Combined_embryos_suitable.obs.groupby(['haniffa_ID','sequencing_lane_ID']).apply(len))
Cell_numbers_table = pd.DataFrame(Combined_embryos_suitable.obs.groupby(['haniffa_ID','sequencing_lane_ID']).apply(len))
Cell_numbers_table.rename(columns = {0:'No_Cells'}, inplace = True)
Cell_numbers_table.to_csv(Metadata_out_path + 'Combined_Embryos_all_suitable_lanes_raw_cell_numbers_per_lane_' + date + '.csv')

Column dtypes:
<class 'anndata._core.views.DataFrameView'>
Index: 1183081 entries, AAACCTGAGATCCGAG-WS_wEMB10202336 to TTTGTCATCCTTCAAT-WS_wEMB12142155
Data columns (total 2 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   sequencing_lane_ID  1183081 non-null  category
 1   haniffa_ID          1183081 non-null  category
dtypes: category(2)
memory usage: 12.4+ MB

None

Number of cells grouped by: embryo -> sequencing lane:

haniffa_ID  sequencing_lane_ID
F137        WS_wEMB10202336        2068
            WS_wEMB10202337        9303
            WS_wEMB10202338        9380
            WS_wEMB10202339        9223
            WS_wEMB10202340        7515
            WS_wEMB10202341        9679
            WS_wEMB10202342       10539
            WS_wEMB10202343        9504
            WS_wEMB10202344        9489
            WS_wEMB10202345        6809
            WS_wEMB10202346        6498
            WS_wEMB10202347        6866
            WS_wEMB10202348        8410
            WS_wEMB10202349        6688
            WS_wEMB10202350        6349
            WS_wEMB10202351        6563
            WS_wEMB10202352        7549
            WS_wEMB10202353        7314
            WS_wEMB10202354        7376
            WS_wEMB10202355        8433
            WS_wEMB10202356        6559
            WS_wEMB10202357        7380
            WS_wEMB10202358        6899
            WS_wEMB10202359        7029
            WS_wEMB10202361        7021
            WS_wEMB10202362        6748
            WS_wEMB10202363        6614
            WS_wEMB10202364        6666
            WS_wEMB10202365        6943
            WS_wEMB10202366        5675
            WS_wEMB10202367        5838
            WS_wEMB10202368        5545
            WS_wEMB10202369        6273
            WS_wEMB10202370        6568
            WS_wEMB10202371        6314
            WS_wEMB10202372        6186
            WS_wEMB10202373        6372
            WS_wEMB10202374        7686
            WS_wEMB10202375        5978
            WS_wEMB10202376        6280
            WS_wEMB10202377        6702
            WS_wEMB10202378        7510
            WS_wEMB10202379        6866
            WS_wEMB10202380        6751
F147        WS_wEMB11031919        9471
            WS_wEMB11031920       13750
            WS_wEMB11031921       13259
            WS_wEMB11031922        8357
            WS_wEMB11031923        4206
            WS_wEMB11031924       13282
            WS_wEMB11031925       12793
            WS_wEMB11031926       10891
            WS_wEMB11031927       11651
            WS_wEMB11031928       12849
            WS_wEMB11031929       10679
            WS_wEMB11031930        8753
            WS_wEMB11031931        8848
            WS_wEMB11031932       13763
            WS_wEMB11031933        9605
            WS_wEMB11031934        9007
            WS_wEMB11031935        5599
            WS_wEMB11031936        7079
            WS_wEMB11031937        8254
            WS_wEMB11031938       11872
            WS_wEMB11031939       10946
            WS_wEMB11031940        7628
            WS_wEMB11031941        7440
            WS_wEMB11031942       11663
            WS_wEMB11031944        8322
            WS_wEMB11031945        7541
            WS_wEMB11031946       12953
            WS_wEMB11031947        7800
            WS_wEMB11031948        7515
            WS_wEMB11031949        8473
            WS_wEMB11031950       19507
            WS_wEMB11031951       14126
            WS_wEMB11031952        7765
            WS_wEMB11031953       11105
            WS_wEMB11031954        7171
            WS_wEMB11031955       11750
            WS_wEMB11031956       14029
            WS_wEMB11031957       10631
            WS_wEMB11031958        9751
            WS_wEMB11031959        7663
            WS_wEMB11031960        6810
            WS_wEMB11031961        8893
            WS_wEMB11031962        6543
            WS_wEMB11031963        7300
            WS_wEMB11031964        8125
            WS_wEMB11031965        8660
            WS_wEMB11031966        8526
F158        WS_wEMB12142105       10357
            WS_wEMB12142106       10456
            WS_wEMB12142107        9114
            WS_wEMB12142108        7090
            WS_wEMB12142109        8353
            WS_wEMB12142110       11418
            WS_wEMB12142111        7906
            WS_wEMB12142112        7465
            WS_wEMB12142113        8469
            WS_wEMB12142114       10648
            WS_wEMB12142115        7249
            WS_wEMB12142116        7019
            WS_wEMB12142117        9226
            WS_wEMB12142118        9654
            WS_wEMB12142119        7283
            WS_wEMB12142120        8781
            WS_wEMB12142121        9796
            WS_wEMB12142122        9023
            WS_wEMB12142123        7411
            WS_wEMB12142124        6431
            WS_wEMB12142125        8058
            WS_wEMB12142126        8944
            WS_wEMB12142127        7610
            WS_wEMB12142128        6584
            WS_wEMB12142129        9669
            WS_wEMB12142130        8618
            WS_wEMB12142131        7566
            WS_wEMB12142135        8332
            WS_wEMB12142136        9830
            WS_wEMB12142137        8461
            WS_wEMB12142138        8443
            WS_wEMB12142139        7826
            WS_wEMB12142140        8250
            WS_wEMB12142141        8769
            WS_wEMB12142142        4197
            WS_wEMB12142143        8315
            WS_wEMB12142144        7851
            WS_wEMB12142145        7807
            WS_wEMB12142146        8674
            WS_wEMB12142147       10439
            WS_wEMB12142148       11565
            WS_wEMB12142149        8276
            WS_wEMB12142150        8083
            WS_wEMB12142151        8891
            WS_wEMB12142152        7492
            WS_wEMB12142153        7615
            WS_wEMB12142154        7803
            WS_wEMB12142155        9402
dtype: int64

## Save anndata object: Combined anndata object
- Saving version of anndata object with all embryos together
- This object has unsuitable lanes for downstream analysis removed
- This object has cellranger raw counts
- This will be used for downstream analysis

In [ ]:
Combined_embryos_suitable.write_h5ad(Objects_out_path + 'Combined_Embryos_all_suitable_lanes_raw_counts_' + date + '.h5ad')

***
### Dependencies
Here are some information about resources and import package versions used within this script

In [1]:
%load_ext watermark
%watermark -v -m -p numpy,pandas,scanpy,anndata

Python implementation: CPython
Python version       : 3.9.4
IPython version      : 7.24.1

numpy  : 1.20.3
pandas : 1.2.4
scanpy : 1.7.2
anndata: 0.7.6

Compiler    : GCC 9.3.0
OS          : Linux
Release     : 4.15.0-112-generic
Machine     : x86_64
Processor   : x86_64
CPU cores   : 26
Architecture: 64bit