 <font size="10">**Notebook 02: Ambient RNA investigation: part 2**</font>
***

<div class="alert alert-info">
    
<b> <h1> ℹ️ <strong> <font size="6" color="black"> Important notebook information </font> </strong> </h1> </b>
    <hr>
    <font size="4" color="black">
        The purpose of this notebook is to generate anndata objects which can then be used to investigate the amount of ambient RNA contribution / "soup" <br> <br>
        This notebook will also look at some basic information for each donor comparing the Cellbender <b>filtered</b> to Cellranger <b>non-filtered intersecting</b> outs <br> <br>
    As Cellbender was run on a per lane basis this investigation is being done on a per donor basis <br> <br>
    The following donors anndata objects will be made for: </font> <br> 
    <ol> <font size="3" color="black">
        <li><b>F137</b> : Embryo_1</li>
        <li><b>F147</b> : Embryo_2</li>
        <li><b>F158</b> : Embryo_3 </li>
    </font> 
    </ol>

# Import packages

In [ ]:
import numpy as np
import pandas as pd
import scanpy as sc
import os

# Set path to embryo matricies (F137 and F147)

In [ ]:
# for embryo 1 and 2
cellbender_outputs = '/home/jovyan/mounting_point/Newcastle_1TB/newcastle/AntonyRose/tic-1254-results/'

# Read in cellbender lane outs for F137

In [ ]:
adata_list1 = []
for i in list(range(36,81)):
    n = 'WS_wEMB102023'+str(i)
    
    if (n == 'WS_wEMB10202360'): # Lanes not passed cellranger therefore no cellbender output
        continue
    
    print(f'Loading in data: {n}')
    data = sc.read_10x_h5(cellbender_outputs + n + '/outs' + '/cellbender_out_filtered.h5')
    print('Making variable names unique')
    data.var_names_make_unique()
    data.obs['sequencing_lane_ID'] = n
    adata_list1.append(data)
    print(f'Data {n} loaded successfully. Data shape is {data.shape}')
    print("")
    del data # to try and prevent stackoverflow

Embryo1 = sc.AnnData.concatenate(*adata_list1, join = 'inner', batch_key = None, batch_categories = None, index_unique = None)
Embryo1.obs.index = Embryo1.obs.index.str.replace('-1','',regex=True)
Embryo1.obs.index = Embryo1.obs.index + '-' + Embryo1.obs['sequencing_lane_ID']
#Embryo1.var['genome'] = 'GRCh38'
print("")
print(f'Embryo1 made successfully')
print("")

Loading in data: WS_wEMB10202336

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202336 loaded successfully. Data shape is (2944, 36601)

Loading in data: WS_wEMB10202337

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202337 loaded successfully. Data shape is (11729, 36601)

Loading in data: WS_wEMB10202338

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202338 loaded successfully. Data shape is (10639, 36601)

Loading in data: WS_wEMB10202339

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202339 loaded successfully. Data shape is (10833, 36601)

Loading in data: WS_wEMB10202340

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202340 loaded successfully. Data shape is (9473, 36601)

Loading in data: WS_wEMB10202341

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202341 loaded successfully. Data shape is (10376, 36601)

Loading in data: WS_wEMB10202342

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202342 loaded successfully. Data shape is (11260, 36601)

Loading in data: WS_wEMB10202343

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202343 loaded successfully. Data shape is (10287, 36601)

Loading in data: WS_wEMB10202344

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202344 loaded successfully. Data shape is (10454, 36601)

Loading in data: WS_wEMB10202345

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202345 loaded successfully. Data shape is (7359, 36601)

Loading in data: WS_wEMB10202346

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202346 loaded successfully. Data shape is (6961, 36601)

Loading in data: WS_wEMB10202347

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202347 loaded successfully. Data shape is (7283, 36601)

Loading in data: WS_wEMB10202348

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202348 loaded successfully. Data shape is (9114, 36601)

Loading in data: WS_wEMB10202349

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202349 loaded successfully. Data shape is (7319, 36601)

Loading in data: WS_wEMB10202350

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202350 loaded successfully. Data shape is (7184, 36601)

Loading in data: WS_wEMB10202351

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202351 loaded successfully. Data shape is (7325, 36601)

Loading in data: WS_wEMB10202352

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202352 loaded successfully. Data shape is (7952, 36601)

Loading in data: WS_wEMB10202353

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202353 loaded successfully. Data shape is (7603, 36601)

Loading in data: WS_wEMB10202354

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202354 loaded successfully. Data shape is (7794, 36601)

Loading in data: WS_wEMB10202355

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202355 loaded successfully. Data shape is (8938, 36601)

Loading in data: WS_wEMB10202356

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202356 loaded successfully. Data shape is (7270, 36601)

Loading in data: WS_wEMB10202357

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202357 loaded successfully. Data shape is (8023, 36601)

Loading in data: WS_wEMB10202358

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202358 loaded successfully. Data shape is (7814, 36601)

Loading in data: WS_wEMB10202359

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202359 loaded successfully. Data shape is (7857, 36601)

Loading in data: WS_wEMB10202361

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202361 loaded successfully. Data shape is (7755, 36601)

Loading in data: WS_wEMB10202362

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202362 loaded successfully. Data shape is (7380, 36601)

Loading in data: WS_wEMB10202363

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202363 loaded successfully. Data shape is (7468, 36601)

Loading in data: WS_wEMB10202364

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202364 loaded successfully. Data shape is (7436, 36601)

Loading in data: WS_wEMB10202365

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202365 loaded successfully. Data shape is (11520, 36601)

Loading in data: WS_wEMB10202366

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202366 loaded successfully. Data shape is (6362, 36601)

Loading in data: WS_wEMB10202367

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202367 loaded successfully. Data shape is (6382, 36601)

Loading in data: WS_wEMB10202368

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202368 loaded successfully. Data shape is (6172, 36601)

Loading in data: WS_wEMB10202369

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202369 loaded successfully. Data shape is (7468, 36601)

Loading in data: WS_wEMB10202370

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202370 loaded successfully. Data shape is (7581, 36601)

Loading in data: WS_wEMB10202371

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202371 loaded successfully. Data shape is (7459, 36601)

Loading in data: WS_wEMB10202372

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202372 loaded successfully. Data shape is (6832, 36601)

Loading in data: WS_wEMB10202373

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202373 loaded successfully. Data shape is (7695, 36601)

Loading in data: WS_wEMB10202374

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202374 loaded successfully. Data shape is (9064, 36601)

Loading in data: WS_wEMB10202375

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202375 loaded successfully. Data shape is (7591, 36601)

Loading in data: WS_wEMB10202376

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202376 loaded successfully. Data shape is (7963, 36601)

Loading in data: WS_wEMB10202377

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202377 loaded successfully. Data shape is (7749, 36601)

Loading in data: WS_wEMB10202378

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202378 loaded successfully. Data shape is (8635, 36601)

Loading in data: WS_wEMB10202379

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202379 loaded successfully. Data shape is (7871, 36601)

Loading in data: WS_wEMB10202380

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB10202380 loaded successfully. Data shape is (7551, 36601)

Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.

Embryo1 made successfully

# Save F137 cellbender object

In [ ]:
Embryo1.write_h5ad('/home/jovyan/mounting_point/Newcastle_1TB/newcastle/AntonyRose/Embryo_objects/Cellbender_Embryo1_all_lanes_passed_cellranger_raw_counts_20220121.h5ad')

... storing 'sequencing_lane_ID' as categorical
... storing 'feature_types' as categorical
... storing 'genome' as categorical

# Read in cellbender lane outs for F147

In [ ]:
adata_list2 = []
for i in list(range(19,67)):
    n = 'WS_wEMB110319'+str(i)
    
    if (n == 'WS_wEMB11031943'): # Lanes not passed cellranger therefore no cellbender output
        continue
    
    print(f'Loading in data: {n}')
    data = sc.read_10x_h5(cellbender_outputs + n + '/outs' + '/cellbender_out_filtered.h5')
    print('Making variable names unique')
    data.var_names_make_unique()
    data.obs['sequencing_lane_ID'] = n
    adata_list2.append(data)
    print(f'Data {n} loaded successfully. Data shape is {data.shape}')
    print("")
    del data # to try and prevent stackoverflow

Embryo2 = sc.AnnData.concatenate(*adata_list2, join = 'inner', batch_key = None, batch_categories = None, index_unique = None)
Embryo2.obs.index = Embryo2.obs.index.str.replace('-1','',regex=True)
Embryo2.obs.index = Embryo2.obs.index + '-' + Embryo2.obs['sequencing_lane_ID']
Embryo2.var['genome'] = 'GRCh38'
print("")
print(f'Embryo2 made successfully')
print("")

Loading in data: WS_wEMB11031919

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031919 loaded successfully. Data shape is (10485, 36601)

Loading in data: WS_wEMB11031920

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031920 loaded successfully. Data shape is (14251, 36601)

Loading in data: WS_wEMB11031921

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031921 loaded successfully. Data shape is (14285, 36601)

Loading in data: WS_wEMB11031922

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031922 loaded successfully. Data shape is (8822, 36601)

Loading in data: WS_wEMB11031923

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031923 loaded successfully. Data shape is (6408, 36601)

Loading in data: WS_wEMB11031924

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031924 loaded successfully. Data shape is (13570, 36601)

Loading in data: WS_wEMB11031925

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031925 loaded successfully. Data shape is (14439, 36601)

Loading in data: WS_wEMB11031926

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031926 loaded successfully. Data shape is (11173, 36601)

Loading in data: WS_wEMB11031927

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031927 loaded successfully. Data shape is (13019, 36601)

Loading in data: WS_wEMB11031928

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031928 loaded successfully. Data shape is (13744, 36601)

Loading in data: WS_wEMB11031929

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031929 loaded successfully. Data shape is (11393, 36601)

Loading in data: WS_wEMB11031930

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031930 loaded successfully. Data shape is (8806, 36601)

Loading in data: WS_wEMB11031931

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031931 loaded successfully. Data shape is (10296, 36601)

Loading in data: WS_wEMB11031932

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031932 loaded successfully. Data shape is (14109, 36601)

Loading in data: WS_wEMB11031933

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031933 loaded successfully. Data shape is (11385, 36601)

Loading in data: WS_wEMB11031934

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031934 loaded successfully. Data shape is (9128, 36601)

Loading in data: WS_wEMB11031935

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031935 loaded successfully. Data shape is (7103, 36601)

Loading in data: WS_wEMB11031936

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031936 loaded successfully. Data shape is (8304, 36601)

Loading in data: WS_wEMB11031937

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031937 loaded successfully. Data shape is (9497, 36601)

Loading in data: WS_wEMB11031938

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031938 loaded successfully. Data shape is (13417, 36601)

Loading in data: WS_wEMB11031939

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031939 loaded successfully. Data shape is (12813, 36601)

Loading in data: WS_wEMB11031940

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031940 loaded successfully. Data shape is (8982, 36601)

Loading in data: WS_wEMB11031941

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031941 loaded successfully. Data shape is (9551, 36601)

Loading in data: WS_wEMB11031942

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031942 loaded successfully. Data shape is (14981, 36601)

Loading in data: WS_wEMB11031944

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031944 loaded successfully. Data shape is (9611, 36601)

Loading in data: WS_wEMB11031945

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031945 loaded successfully. Data shape is (10848, 36601)

Loading in data: WS_wEMB11031946

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031946 loaded successfully. Data shape is (18126, 36601)

Loading in data: WS_wEMB11031947

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031947 loaded successfully. Data shape is (9540, 36601)

Loading in data: WS_wEMB11031948

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031948 loaded successfully. Data shape is (9086, 36601)

Loading in data: WS_wEMB11031949

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031949 loaded successfully. Data shape is (12303, 36601)

Loading in data: WS_wEMB11031950

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031950 loaded successfully. Data shape is (29557, 36601)

Loading in data: WS_wEMB11031951

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031951 loaded successfully. Data shape is (16252, 36601)

Loading in data: WS_wEMB11031952

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031952 loaded successfully. Data shape is (8999, 36601)

Loading in data: WS_wEMB11031953

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031953 loaded successfully. Data shape is (12459, 36601)

Loading in data: WS_wEMB11031954

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031954 loaded successfully. Data shape is (8160, 36601)

Loading in data: WS_wEMB11031955

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031955 loaded successfully. Data shape is (13083, 36601)

Loading in data: WS_wEMB11031956

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031956 loaded successfully. Data shape is (16909, 36601)

Loading in data: WS_wEMB11031957

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031957 loaded successfully. Data shape is (12191, 36601)

Loading in data: WS_wEMB11031958

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031958 loaded successfully. Data shape is (11801, 36601)

Loading in data: WS_wEMB11031959

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031959 loaded successfully. Data shape is (9003, 36601)

Loading in data: WS_wEMB11031960

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031960 loaded successfully. Data shape is (8771, 36601)

Loading in data: WS_wEMB11031961

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031961 loaded successfully. Data shape is (9788, 36601)

Loading in data: WS_wEMB11031962

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031962 loaded successfully. Data shape is (7621, 36601)

Loading in data: WS_wEMB11031963

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031963 loaded successfully. Data shape is (8166, 36601)

Loading in data: WS_wEMB11031964

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031964 loaded successfully. Data shape is (10177, 36601)

Loading in data: WS_wEMB11031965

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031965 loaded successfully. Data shape is (10020, 36601)

Loading in data: WS_wEMB11031966

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB11031966 loaded successfully. Data shape is (10099, 36601)

Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.

Embryo2 made successfully

# Save F147 cellbender object

In [ ]:
Embryo2.write_h5ad('/home/jovyan/mounting_point/Newcastle_1TB/newcastle/AntonyRose/Embryo_objects/Cellbender_Embryo2_all_lanes_passed_cellranger_raw_counts_20220121.h5ad')

... storing 'sequencing_lane_ID' as categorical
... storing 'feature_types' as categorical
... storing 'genome' as categorical

# Check counts for both embryo F137 and F147 compared to cellranger

In [ ]:
import numpy as np
import pandas as pd
import scanpy as sc
import os

# Calculate for F137

In [ ]:
Embryo1_cellbender_matricies = []

Embryo1_outs_comp = pd.DataFrame(columns=('Sample', 'n_cells', 'cellranger reads raw', 'cellbender reads filt', 'percent filtered'))
for i in list(range(36,81)):
    n = 'WS_wEMB102023'+str(i)
    
    if (n == 'WS_wEMB10202360'): # Lanes not passed cellranger therefore no cellbender output
        continue
    
    print(f'Starting loop for sample: {n}')
    print('Reading in cellranger raw matrix:')
    cellranger_raw_ = sc.read_10x_h5('/home/jovyan/mounting_point/Newcastle_1TB/newcastle/AntonyRose/uncompressed_embryo/embryo1/' + n + '/raw_feature_bc_matrix.h5')
    print('Making variable names unique')
    cellranger_raw_.var_names_make_unique()
    print('Cell ranger raw matrix loaded successfully')
    print()
    print('Reading in cell bender filtered matrix:')
    cellbender_filt = sc.read_10x_h5('/home/jovyan/mounting_point/Newcastle_1TB/newcastle/AntonyRose/tic-1254-results/' + n + '/outs/cellbender_out_filtered.h5')
    print('Making variable names unique')
    cellbender_filt.var_names_make_unique()
    print('Cell bender filt matrix loaded successfully')
    print()
    print('Proceeding to compare the two matricies counts values:')
    
    cellranger_raw_ = cellranger_raw_[cellranger_raw_.obs.index.isin(list(cellbender_filt.obs.index))]
    n_cells = len(cellbender_filt.obs)
    
    data = cellbender_filt
    UMI_filt = pd.DataFrame(data.X.todense())
    #UMI_filt.index = data.obs.index
    #UMI_filt.columns = data.var.index
    UMI_filt_sum = sum(UMI_filt.sum(axis=1))
    
    data = cellranger_raw_
    UMI_raw = pd.DataFrame(data.X.todense())
    #UMI_raw.index = data.obs.index
    #UMI_raw.columns = data.var.index
    UMI_raw_sum = sum(UMI_raw.sum(axis=1))
    
    if (UMI_filt_sum == UMI_raw_sum):
        raise Exception('Both matricies match - not good!!!')
    
    percent_filt = round(((UMI_raw_sum-UMI_filt_sum)/UMI_raw_sum)*100,2)
    print(f'Stats for sample {n}: {n_cells} cells, {UMI_raw_sum} reads (raw), {UMI_filt_sum} reads (filt), {percent_filt}% filtered')
    table = pd.DataFrame({'Sample':[n], 'n_cells':[n_cells], 'cellranger reads raw':[UMI_raw_sum], 'cellbender reads filt':[UMI_filt_sum], 'percent filtered':[percent_filt]})
    Embryo1_outs_comp = pd.concat([Embryo1_outs_comp,table])
    print()
    print('Loop complete')
    print()
    #del cellranger_raw_
    #del cellbender_filt
    #del data
    #del UMI_raw
    #del UMI_filt

Starting loop for sample: WS_wEMB10202336
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202336: 2944 cells, 24531066.0 reads (raw), 24485917.0 reads (filt), 0.18% filtered

Loop complete

Starting loop for sample: WS_wEMB10202337
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202337: 11729 cells, 135642191.0 reads (raw), 135411066.0 reads (filt), 0.17% filtered

Loop complete

Starting loop for sample: WS_wEMB10202338
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202338: 10639 cells, 154649301.0 reads (raw), 154384056.0 reads (filt), 0.17% filtered

Loop complete

Starting loop for sample: WS_wEMB10202339
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202339: 10833 cells, 150333121.0 reads (raw), 150100285.0 reads (filt), 0.15% filtered

Loop complete

Starting loop for sample: WS_wEMB10202340
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202340: 9473 cells, 111161034.0 reads (raw), 110992986.0 reads (filt), 0.15% filtered

Loop complete

Starting loop for sample: WS_wEMB10202341
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202341: 10376 cells, 113730072.0 reads (raw), 113526022.0 reads (filt), 0.18% filtered

Loop complete

Starting loop for sample: WS_wEMB10202342
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202342: 11260 cells, 161623574.0 reads (raw), 161372078.0 reads (filt), 0.16% filtered

Loop complete

Starting loop for sample: WS_wEMB10202343
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202343: 10287 cells, 116396000.0 reads (raw), 116271106.0 reads (filt), 0.11% filtered

Loop complete

Starting loop for sample: WS_wEMB10202344
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202344: 10454 cells, 151689189.0 reads (raw), 151522193.0 reads (filt), 0.11% filtered

Loop complete

Starting loop for sample: WS_wEMB10202345
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202345: 7359 cells, 147640329.0 reads (raw), 147366735.0 reads (filt), 0.19% filtered

Loop complete

Starting loop for sample: WS_wEMB10202346
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202346: 6961 cells, 128183820.0 reads (raw), 127930287.0 reads (filt), 0.2% filtered

Loop complete

Starting loop for sample: WS_wEMB10202347
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202347: 7283 cells, 155107926.0 reads (raw), 154757511.0 reads (filt), 0.23% filtered

Loop complete

Starting loop for sample: WS_wEMB10202348
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202348: 9114 cells, 134310512.0 reads (raw), 134081649.0 reads (filt), 0.17% filtered

Loop complete

Starting loop for sample: WS_wEMB10202349
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202349: 7319 cells, 98991843.0 reads (raw), 98916133.0 reads (filt), 0.08% filtered

Loop complete

Starting loop for sample: WS_wEMB10202350
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202350: 7184 cells, 91569856.0 reads (raw), 91517533.0 reads (filt), 0.06% filtered

Loop complete

Starting loop for sample: WS_wEMB10202351
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202351: 7325 cells, 106786992.0 reads (raw), 106689004.0 reads (filt), 0.09% filtered

Loop complete

Starting loop for sample: WS_wEMB10202352
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202352: 7952 cells, 109779203.0 reads (raw), 109631531.0 reads (filt), 0.13% filtered

Loop complete

Starting loop for sample: WS_wEMB10202353
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202353: 7603 cells, 116835766.0 reads (raw), 116609849.0 reads (filt), 0.19% filtered

Loop complete

Starting loop for sample: WS_wEMB10202354
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202354: 7794 cells, 115402259.0 reads (raw), 115278666.0 reads (filt), 0.11% filtered

Loop complete

Starting loop for sample: WS_wEMB10202355
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202355: 8938 cells, 130777318.0 reads (raw), 130652703.0 reads (filt), 0.1% filtered

Loop complete

Starting loop for sample: WS_wEMB10202356
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202356: 7270 cells, 102262587.0 reads (raw), 102179042.0 reads (filt), 0.08% filtered

Loop complete

Starting loop for sample: WS_wEMB10202357
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202357: 8023 cells, 126119710.0 reads (raw), 126000931.0 reads (filt), 0.09% filtered

Loop complete

Starting loop for sample: WS_wEMB10202358
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202358: 7814 cells, 118752112.0 reads (raw), 118647103.0 reads (filt), 0.09% filtered

Loop complete

Starting loop for sample: WS_wEMB10202359
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202359: 7857 cells, 109405777.0 reads (raw), 109304345.0 reads (filt), 0.09% filtered

Loop complete

Starting loop for sample: WS_wEMB10202361
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202361: 7755 cells, 114820529.0 reads (raw), 114726733.0 reads (filt), 0.08% filtered

Loop complete

Starting loop for sample: WS_wEMB10202362
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202362: 7380 cells, 100459987.0 reads (raw), 100382085.0 reads (filt), 0.08% filtered

Loop complete

Starting loop for sample: WS_wEMB10202363
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202363: 7468 cells, 100471983.0 reads (raw), 100407939.0 reads (filt), 0.06% filtered

Loop complete

Starting loop for sample: WS_wEMB10202364
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202364: 7436 cells, 103914302.0 reads (raw), 103834182.0 reads (filt), 0.08% filtered

Loop complete

Starting loop for sample: WS_wEMB10202365
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202365: 11520 cells, 66391494.0 reads (raw), 66343020.0 reads (filt), 0.07% filtered

Loop complete

Starting loop for sample: WS_wEMB10202366
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202366: 6362 cells, 83605615.0 reads (raw), 83536126.0 reads (filt), 0.08% filtered

Loop complete

Starting loop for sample: WS_wEMB10202367
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202367: 6382 cells, 82617374.0 reads (raw), 82537131.0 reads (filt), 0.1% filtered

Loop complete

Starting loop for sample: WS_wEMB10202368
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202368: 6172 cells, 88666080.0 reads (raw), 88586028.0 reads (filt), 0.09% filtered

Loop complete

Starting loop for sample: WS_wEMB10202369
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202369: 7468 cells, 96747400.0 reads (raw), 96574675.0 reads (filt), 0.18% filtered

Loop complete

Starting loop for sample: WS_wEMB10202370
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202370: 7581 cells, 98745321.0 reads (raw), 98610493.0 reads (filt), 0.14% filtered

Loop complete

Starting loop for sample: WS_wEMB10202371
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202371: 7459 cells, 74788764.0 reads (raw), 74706603.0 reads (filt), 0.11% filtered

Loop complete

Starting loop for sample: WS_wEMB10202372
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202372: 6832 cells, 91709306.0 reads (raw), 91553248.0 reads (filt), 0.17% filtered

Loop complete

Starting loop for sample: WS_wEMB10202373
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202373: 7695 cells, 95579151.0 reads (raw), 95414859.0 reads (filt), 0.17% filtered

Loop complete

Starting loop for sample: WS_wEMB10202374
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202374: 9064 cells, 129227873.0 reads (raw), 128767442.0 reads (filt), 0.36% filtered

Loop complete

Starting loop for sample: WS_wEMB10202375
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202375: 7591 cells, 94623690.0 reads (raw), 94422456.0 reads (filt), 0.21% filtered

Loop complete

Starting loop for sample: WS_wEMB10202376
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202376: 7963 cells, 83940873.0 reads (raw), 83774447.0 reads (filt), 0.2% filtered

Loop complete

Starting loop for sample: WS_wEMB10202377
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202377: 7749 cells, 128047732.0 reads (raw), 127820101.0 reads (filt), 0.18% filtered

Loop complete

Starting loop for sample: WS_wEMB10202378
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202378: 8635 cells, 147186865.0 reads (raw), 146889776.0 reads (filt), 0.2% filtered

Loop complete

Starting loop for sample: WS_wEMB10202379
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202379: 7871 cells, 126227956.0 reads (raw), 126047109.0 reads (filt), 0.14% filtered

Loop complete

Starting loop for sample: WS_wEMB10202380
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB10202380: 7551 cells, 129458874.0 reads (raw), 129036306.0 reads (filt), 0.33% filtered

Loop complete

# Calculate for F147

In [ ]:
Embryo2_outs_comp = pd.DataFrame(columns=('Sample', 'n_cells', 'cellranger reads raw', 'cellbender reads filt', 'percent filtered'))
for i in list(range(19,67)):
    n = 'WS_wEMB110319'+str(i)
    
    if (n == 'WS_wEMB11031943'): # Lanes not passed cellranger therefore no cellbender output
        continue
    
    print(f'Starting loop for sample: {n}')
    print('Reading in cellranger raw matrix:')
    cellranger_raw_ = sc.read_10x_h5('/home/jovyan/mounting_point/Newcastle_1TB/newcastle/AntonyRose/uncompressed_embryo/embryo2/cellranger/' + n + '/raw_feature_bc_matrix.h5')
    print('Making variable names unique')
    cellranger_raw_.var_names_make_unique()
    print('Cell ranger raw matrix loaded successfully')
    print()
    print('Reading in cell bender filtered matrix:')
    cellbender_filt = sc.read_10x_h5('/home/jovyan/mounting_point/Newcastle_1TB/newcastle/AntonyRose/tic-1254-results/' + n + '/outs/cellbender_out_filtered.h5')
    print('Making variable names unique')
    cellbender_filt.var_names_make_unique()
    print('Cell bender filt matrix loaded successfully')
    print()
    print('Proceeding to compare the two matricies counts values:')
    
    cellranger_raw_ = cellranger_raw_[cellranger_raw_.obs.index.isin(list(cellbender_filt.obs.index))]
    n_cells = len(cellbender_filt.obs)
    
    data = cellbender_filt
    UMI_filt = pd.DataFrame(data.X.todense())
    #UMI_filt.index = data.obs.index
    #UMI_filt.columns = data.var.index
    UMI_filt_sum = sum(UMI_filt.sum(axis=1))
    
    data = cellranger_raw_
    UMI_raw = pd.DataFrame(data.X.todense())
    #UMI_raw.index = data.obs.index
    #UMI_raw.columns = data.var.index
    UMI_raw_sum = sum(UMI_raw.sum(axis=1))
    
    if (UMI_filt_sum == UMI_raw_sum):
        raise Exception('Both matricies match - not good!!!')
    
    percent_filt = round(((UMI_raw_sum-UMI_filt_sum)/UMI_raw_sum)*100,2)
    print(f'Stats for sample {n}: {n_cells} cells, {UMI_raw_sum} reads (raw), {UMI_filt_sum} reads (filt), {percent_filt}% filtered')
    table = pd.DataFrame({'Sample':[n], 'n_cells':[n_cells], 'cellranger reads raw':[UMI_raw_sum], 'cellbender reads filt':[UMI_filt_sum], 'percent filtered':[percent_filt]})
    Embryo2_outs_comp = pd.concat([Embryo2_outs_comp,table])
    print()
    print('Loop complete')
    print()
    #del cellranger_raw_
    #del cellbender_filt
    #del data
    #del UMI_raw
    #del UMI_filt

Starting loop for sample: WS_wEMB11031919
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031919: 10485 cells, 78898874.0 reads (raw), 78426058.0 reads (filt), 0.6% filtered

Loop complete

Starting loop for sample: WS_wEMB11031920
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031920: 14251 cells, 132647383.0 reads (raw), 131838496.0 reads (filt), 0.61% filtered

Loop complete

Starting loop for sample: WS_wEMB11031921
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031921: 14285 cells, 144762897.0 reads (raw), 143788483.0 reads (filt), 0.67% filtered

Loop complete

Starting loop for sample: WS_wEMB11031922
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031922: 8822 cells, 61473767.0 reads (raw), 61313582.0 reads (filt), 0.26% filtered

Loop complete

Starting loop for sample: WS_wEMB11031923
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031923: 6408 cells, 36631735.0 reads (raw), 36549734.0 reads (filt), 0.22% filtered

Loop complete

Starting loop for sample: WS_wEMB11031924
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031924: 13570 cells, 149530533.0 reads (raw), 148432447.0 reads (filt), 0.73% filtered

Loop complete

Starting loop for sample: WS_wEMB11031925
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031925: 14439 cells, 145028334.0 reads (raw), 144384497.0 reads (filt), 0.44% filtered

Loop complete

Starting loop for sample: WS_wEMB11031926
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031926: 11173 cells, 172529852.0 reads (raw), 171895438.0 reads (filt), 0.37% filtered

Loop complete

Starting loop for sample: WS_wEMB11031927
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031927: 13019 cells, 194121078.0 reads (raw), 193236796.0 reads (filt), 0.46% filtered

Loop complete

Starting loop for sample: WS_wEMB11031928
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031928: 13744 cells, 192984367.0 reads (raw), 192073676.0 reads (filt), 0.47% filtered

Loop complete

Starting loop for sample: WS_wEMB11031929
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031929: 11393 cells, 171642426.0 reads (raw), 170902450.0 reads (filt), 0.43% filtered

Loop complete

Starting loop for sample: WS_wEMB11031930
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031930: 8806 cells, 177199774.0 reads (raw), 176637701.0 reads (filt), 0.32% filtered

Loop complete

Starting loop for sample: WS_wEMB11031931
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031931: 10296 cells, 134087378.0 reads (raw), 133631793.0 reads (filt), 0.34% filtered

Loop complete

Starting loop for sample: WS_wEMB11031932
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031932: 14109 cells, 199842479.0 reads (raw), 198414610.0 reads (filt), 0.71% filtered

Loop complete

Starting loop for sample: WS_wEMB11031933
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031933: 11385 cells, 130247251.0 reads (raw), 129945806.0 reads (filt), 0.23% filtered

Loop complete

Starting loop for sample: WS_wEMB11031934
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031934: 9128 cells, 120351954.0 reads (raw), 119779103.0 reads (filt), 0.48% filtered

Loop complete

Starting loop for sample: WS_wEMB11031935
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031935: 7103 cells, 64539855.0 reads (raw), 64486388.0 reads (filt), 0.08% filtered

Loop complete

Starting loop for sample: WS_wEMB11031936
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031936: 8304 cells, 78360270.0 reads (raw), 78203319.0 reads (filt), 0.2% filtered

Loop complete

Starting loop for sample: WS_wEMB11031937
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031937: 9497 cells, 147665857.0 reads (raw), 147567840.0 reads (filt), 0.07% filtered

Loop complete

Starting loop for sample: WS_wEMB11031938
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031938: 13417 cells, 152398107.0 reads (raw), 151116218.0 reads (filt), 0.84% filtered

Loop complete

Starting loop for sample: WS_wEMB11031939
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031939: 12813 cells, 129211049.0 reads (raw), 128829970.0 reads (filt), 0.29% filtered

Loop complete

Starting loop for sample: WS_wEMB11031940
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031940: 8982 cells, 111145337.0 reads (raw), 110927332.0 reads (filt), 0.2% filtered

Loop complete

Starting loop for sample: WS_wEMB11031941
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031941: 9551 cells, 93375343.0 reads (raw), 93311375.0 reads (filt), 0.07% filtered

Loop complete

Starting loop for sample: WS_wEMB11031942
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031942: 14981 cells, 129567832.0 reads (raw), 128323920.0 reads (filt), 0.96% filtered

Loop complete

Starting loop for sample: WS_wEMB11031944
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031944: 9611 cells, 93420135.0 reads (raw), 93200588.0 reads (filt), 0.24% filtered

Loop complete

Starting loop for sample: WS_wEMB11031945
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031945: 10848 cells, 89130108.0 reads (raw), 88999361.0 reads (filt), 0.15% filtered

Loop complete

Starting loop for sample: WS_wEMB11031946
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031946: 18126 cells, 101826698.0 reads (raw), 101326947.0 reads (filt), 0.49% filtered

Loop complete

Starting loop for sample: WS_wEMB11031947
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031947: 9540 cells, 126783530.0 reads (raw), 126656703.0 reads (filt), 0.1% filtered

Loop complete

Starting loop for sample: WS_wEMB11031948
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031948: 9086 cells, 63789993.0 reads (raw), 63628676.0 reads (filt), 0.25% filtered

Loop complete

Starting loop for sample: WS_wEMB11031949
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031949: 12303 cells, 77342394.0 reads (raw), 77230200.0 reads (filt), 0.15% filtered

Loop complete

Starting loop for sample: WS_wEMB11031950
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031950: 29557 cells, 81257774.0 reads (raw), 81108052.0 reads (filt), 0.18% filtered

Loop complete

Starting loop for sample: WS_wEMB11031951
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031951: 16252 cells, 174848015.0 reads (raw), 174596173.0 reads (filt), 0.14% filtered

Loop complete

Starting loop for sample: WS_wEMB11031952
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031952: 8999 cells, 128543336.0 reads (raw), 128309460.0 reads (filt), 0.18% filtered

Loop complete

Starting loop for sample: WS_wEMB11031953
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031953: 12459 cells, 157708702.0 reads (raw), 157520874.0 reads (filt), 0.12% filtered

Loop complete

Starting loop for sample: WS_wEMB11031954
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031954: 8160 cells, 74344534.0 reads (raw), 74229692.0 reads (filt), 0.15% filtered

Loop complete

Starting loop for sample: WS_wEMB11031955
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031955: 13083 cells, 166284277.0 reads (raw), 165551647.0 reads (filt), 0.44% filtered

Loop complete

Starting loop for sample: WS_wEMB11031956
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031956: 16909 cells, 183475725.0 reads (raw), 182512154.0 reads (filt), 0.53% filtered

Loop complete

Starting loop for sample: WS_wEMB11031957
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031957: 12191 cells, 182898337.0 reads (raw), 182696526.0 reads (filt), 0.11% filtered

Loop complete

Starting loop for sample: WS_wEMB11031958
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031958: 11801 cells, 125747084.0 reads (raw), 125409488.0 reads (filt), 0.27% filtered

Loop complete

Starting loop for sample: WS_wEMB11031959
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031959: 9003 cells, 70379399.0 reads (raw), 69675789.0 reads (filt), 1.0% filtered

Loop complete

Starting loop for sample: WS_wEMB11031960
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031960: 8771 cells, 105513137.0 reads (raw), 105442726.0 reads (filt), 0.07% filtered

Loop complete

Starting loop for sample: WS_wEMB11031961
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031961: 9788 cells, 96492851.0 reads (raw), 96363972.0 reads (filt), 0.13% filtered

Loop complete

Starting loop for sample: WS_wEMB11031962
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031962: 7621 cells, 81940732.0 reads (raw), 81843239.0 reads (filt), 0.12% filtered

Loop complete

Starting loop for sample: WS_wEMB11031963
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031963: 8166 cells, 80511815.0 reads (raw), 79697817.0 reads (filt), 1.01% filtered

Loop complete

Starting loop for sample: WS_wEMB11031964
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031964: 10177 cells, 142081744.0 reads (raw), 141937583.0 reads (filt), 0.1% filtered

Loop complete

Starting loop for sample: WS_wEMB11031965
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031965: 10020 cells, 95801936.0 reads (raw), 95728522.0 reads (filt), 0.08% filtered

Loop complete

Starting loop for sample: WS_wEMB11031966
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB11031966: 10099 cells, 119694690.0 reads (raw), 119515011.0 reads (filt), 0.15% filtered

Loop complete

# Look at output

In [ ]:
Embryo1_outs_comp

,Sample,n_cells,cellranger reads raw,cellbender reads filt,percent filtered
0,WS_wEMB10202336,2944,24531066.0,24485917.0,0.18
0,WS_wEMB10202337,11729,135642191.0,135411066.0,0.17
0,WS_wEMB10202338,10639,154649301.0,154384056.0,0.17
0,WS_wEMB10202339,10833,150333121.0,150100285.0,0.15
0,WS_wEMB10202340,9473,111161034.0,110992986.0,0.15
0,WS_wEMB10202341,10376,113730072.0,113526022.0,0.18
0,WS_wEMB10202342,11260,161623574.0,161372078.0,0.16
0,WS_wEMB10202343,10287,116396000.0,116271106.0,0.11
0,WS_wEMB10202344,10454,151689189.0,151522193.0,0.11
0,WS_wEMB10202345,7359,147640329.0,147366735.0,0.19
0,WS_wEMB10202346,6961,128183820.0,127930287.0,0.20
0,WS_wEMB10202347,7283,155107926.0,154757511.0,0.23
0,WS_wEMB10202348,9114,134310512.0,134081649.0,0.17
0,WS_wEMB10202349,7319,98991843.0,98916133.0,0.08
0,WS_wEMB10202350,7184,91569856.0,91517533.0,0.06
0,WS_wEMB10202351,7325,106786992.0,106689004.0,0.09
0,WS_wEMB10202352,7952,109779203.0,109631531.0,0.13
0,WS_wEMB10202353,7603,116835766.0,116609849.0,0.19
0,WS_wEMB10202354,7794,115402259.0,115278666.0,0.11
0,WS_wEMB10202355,8938,130777318.0,130652703.0,0.10
0,WS_wEMB10202356,7270,102262587.0,102179042.0,0.08
0,WS_wEMB10202357,8023,126119710.0,126000931.0,0.09
0,WS_wEMB10202358,7814,118752112.0,118647103.0,0.09
0,WS_wEMB10202359,7857,109405777.0,109304345.0,0.09
0,WS_wEMB10202361,7755,114820529.0,114726733.0,0.08
0,WS_wEMB10202362,7380,100459987.0,100382085.0,0.08
0,WS_wEMB10202363,7468,100471983.0,100407939.0,0.06
0,WS_wEMB10202364,7436,103914302.0,103834182.0,0.08
0,WS_wEMB10202365,11520,66391494.0,66343020.0,0.07
0,WS_wEMB10202366,6362,83605615.0,83536126.0,0.08
0,WS_wEMB10202367,6382,82617374.0,82537131.0,0.10
0,WS_wEMB10202368,6172,88666080.0,88586028.0,0.09
0,WS_wEMB10202369,7468,96747400.0,96574675.0,0.18
0,WS_wEMB10202370,7581,98745321.0,98610493.0,0.14
0,WS_wEMB10202371,7459,74788764.0,74706603.0,0.11
0,WS_wEMB10202372,6832,91709306.0,91553248.0,0.17
0,WS_wEMB10202373,7695,95579151.0,95414859.0,0.17
0,WS_wEMB10202374,9064,129227873.0,128767442.0,0.36
0,WS_wEMB10202375,7591,94623690.0,94422456.0,0.21
0,WS_wEMB10202376,7963,83940873.0,83774447.0,0.20
0,WS_wEMB10202377,7749,128047732.0,127820101.0,0.18
0,WS_wEMB10202378,8635,147186865.0,146889776.0,0.20
0,WS_wEMB10202379,7871,126227956.0,126047109.0,0.14
0,WS_wEMB10202380,7551,129458874.0,129036306.0,0.33

In [ ]:
Embryo2_outs_comp

,Sample,n_cells,cellranger reads raw,cellbender reads filt,percent filtered
0,WS_wEMB11031919,10485,78898874.0,78426058.0,0.60
0,WS_wEMB11031920,14251,132647383.0,131838496.0,0.61
0,WS_wEMB11031921,14285,144762897.0,143788483.0,0.67
0,WS_wEMB11031922,8822,61473767.0,61313582.0,0.26
0,WS_wEMB11031923,6408,36631735.0,36549734.0,0.22
0,WS_wEMB11031924,13570,149530533.0,148432447.0,0.73
0,WS_wEMB11031925,14439,145028334.0,144384497.0,0.44
0,WS_wEMB11031926,11173,172529852.0,171895438.0,0.37
0,WS_wEMB11031927,13019,194121078.0,193236796.0,0.46
0,WS_wEMB11031928,13744,192984367.0,192073676.0,0.47
0,WS_wEMB11031929,11393,171642426.0,170902450.0,0.43
0,WS_wEMB11031930,8806,177199774.0,176637701.0,0.32
0,WS_wEMB11031931,10296,134087378.0,133631793.0,0.34
0,WS_wEMB11031932,14109,199842479.0,198414610.0,0.71
0,WS_wEMB11031933,11385,130247251.0,129945806.0,0.23
0,WS_wEMB11031934,9128,120351954.0,119779103.0,0.48
0,WS_wEMB11031935,7103,64539855.0,64486388.0,0.08
0,WS_wEMB11031936,8304,78360270.0,78203319.0,0.20
0,WS_wEMB11031937,9497,147665857.0,147567840.0,0.07
0,WS_wEMB11031938,13417,152398107.0,151116218.0,0.84
0,WS_wEMB11031939,12813,129211049.0,128829970.0,0.29
0,WS_wEMB11031940,8982,111145337.0,110927332.0,0.20
0,WS_wEMB11031941,9551,93375343.0,93311375.0,0.07
0,WS_wEMB11031942,14981,129567832.0,128323920.0,0.96
0,WS_wEMB11031944,9611,93420135.0,93200588.0,0.24
0,WS_wEMB11031945,10848,89130108.0,88999361.0,0.15
0,WS_wEMB11031946,18126,101826698.0,101326947.0,0.49
0,WS_wEMB11031947,9540,126783530.0,126656703.0,0.10
0,WS_wEMB11031948,9086,63789993.0,63628676.0,0.25
0,WS_wEMB11031949,12303,77342394.0,77230200.0,0.15
0,WS_wEMB11031950,29557,81257774.0,81108052.0,0.18
0,WS_wEMB11031951,16252,174848015.0,174596173.0,0.14
0,WS_wEMB11031952,8999,128543336.0,128309460.0,0.18
0,WS_wEMB11031953,12459,157708702.0,157520874.0,0.12
0,WS_wEMB11031954,8160,74344534.0,74229692.0,0.15
0,WS_wEMB11031955,13083,166284277.0,165551647.0,0.44
0,WS_wEMB11031956,16909,183475725.0,182512154.0,0.53
0,WS_wEMB11031957,12191,182898337.0,182696526.0,0.11
0,WS_wEMB11031958,11801,125747084.0,125409488.0,0.27
0,WS_wEMB11031959,9003,70379399.0,69675789.0,1.00
0,WS_wEMB11031960,8771,105513137.0,105442726.0,0.07
0,WS_wEMB11031961,9788,96492851.0,96363972.0,0.13
0,WS_wEMB11031962,7621,81940732.0,81843239.0,0.12
0,WS_wEMB11031963,8166,80511815.0,79697817.0,1.01
0,WS_wEMB11031964,10177,142081744.0,141937583.0,0.10
0,WS_wEMB11031965,10020,95801936.0,95728522.0,0.08
0,WS_wEMB11031966,10099,119694690.0,119515011.0,0.15

# Add in metadata for each lane for section

In [ ]:
lane_ID_dict_Embryo1 = {
'WS_wEMB10202336' : 'Section_1_a',
'WS_wEMB10202337' : 'Section_2_a',
'WS_wEMB10202338' : 'Section_2_b',
'WS_wEMB10202339' : 'Section_2_c',
'WS_wEMB10202340' : 'Section_2_d',
'WS_wEMB10202341' : 'Section_3_a',
'WS_wEMB10202342' : 'Section_3_b',
'WS_wEMB10202343' : 'Section_3_c',
'WS_wEMB10202344' : 'Section_3_d',
'WS_wEMB10202345' : 'Section_4_a',
'WS_wEMB10202346' : 'Section_4_b',
'WS_wEMB10202347' : 'Section_4_c',
'WS_wEMB10202348' : 'Section_4_d',
'WS_wEMB10202349' : 'Section_5_a',
'WS_wEMB10202350' : 'Section_5_b',
'WS_wEMB10202351' : 'Section_5_c',
'WS_wEMB10202352' : 'Section_5_d',
'WS_wEMB10202353' : 'Section_6_a',
'WS_wEMB10202354' : 'Section_6_b',
'WS_wEMB10202355' : 'Section_6_c',
'WS_wEMB10202356' : 'Section_6_d',
'WS_wEMB10202357' : 'Section_7_a',
'WS_wEMB10202358' : 'Section_7_b',
'WS_wEMB10202359' : 'Section_7_c',
'WS_wEMB10202360' : 'Section_7_d',
'WS_wEMB10202361' : 'Section_8_a',
'WS_wEMB10202362' : 'Section_8_b',
'WS_wEMB10202363' : 'Section_8_c',
'WS_wEMB10202364' : 'Section_8_d',
'WS_wEMB10202365' : 'Section_9_a',
'WS_wEMB10202366' : 'Section_9_b',
'WS_wEMB10202367' : 'Section_9_c',
'WS_wEMB10202368' : 'Section_9_d',
'WS_wEMB10202369' : 'Section_10_a',
'WS_wEMB10202370' : 'Section_10_b',
'WS_wEMB10202371' : 'Section_10_c',
'WS_wEMB10202372' : 'Section_10_d',
'WS_wEMB10202373' : 'Section_11_a',
'WS_wEMB10202374' : 'Section_11_b',
'WS_wEMB10202375' : 'Section_11_c',
'WS_wEMB10202376' : 'Section_11_d',
'WS_wEMB10202377' : 'Section_12_a',
'WS_wEMB10202378' : 'Section_12_b',
'WS_wEMB10202379' : 'Section_12_c',
'WS_wEMB10202380' : 'Section_12_d'
}

lane_ID_dict_Embryo2 = {
'WS_wEMB11031919' : 'Section_1_A',
'WS_wEMB11031920' : 'Section_2_A',
'WS_wEMB11031921' : 'Section_3_A',
'WS_wEMB11031922' : 'Section_4_A',
'WS_wEMB11031923' : 'Section_1_B',
'WS_wEMB11031924' : 'Section_2_B',
'WS_wEMB11031925' : 'Section_3_B',
'WS_wEMB11031926' : 'Section_4_B',
'WS_wEMB11031927' : 'Section_1_C',
'WS_wEMB11031928' : 'Section_2_C',
'WS_wEMB11031929' : 'Section_3_C',
'WS_wEMB11031930' : 'Section_4_C',
'WS_wEMB11031931' : 'Section_1_D',
'WS_wEMB11031932' : 'Section_2_D',
'WS_wEMB11031933' : 'Section_3_D',
'WS_wEMB11031934' : 'Section_4_D',
'WS_wEMB11031935' : 'Section_5_A',
'WS_wEMB11031936' : 'Section_6_A',
'WS_wEMB11031937' : 'Section_7_A',
'WS_wEMB11031938' : 'Section_8_A',
'WS_wEMB11031939' : 'Section_5_B',
'WS_wEMB11031940' : 'Section_6_B',
'WS_wEMB11031941' : 'Section_7_B',
'WS_wEMB11031942' : 'Section_8_B',
'WS_wEMB11031943' : 'Section_5_C',
'WS_wEMB11031944' : 'Section_6_C',
'WS_wEMB11031945' : 'Section_7_C',
'WS_wEMB11031946' : 'Section_8_C',
'WS_wEMB11031947' : 'Section_5_D',
'WS_wEMB11031948' : 'Section_6_D',
'WS_wEMB11031949' : 'Section_7_D',
'WS_wEMB11031950' : 'Section_8_D',
'WS_wEMB11031951' : 'Section_9_A',
'WS_wEMB11031952' : 'Section_10_A',
'WS_wEMB11031953' : 'Section_11_A',
'WS_wEMB11031954' : 'Section_12_A',
'WS_wEMB11031955' : 'Section_9_B',
'WS_wEMB11031956' : 'Section_10_B',
'WS_wEMB11031957' : 'Section_11_B',
'WS_wEMB11031958' : 'Section_12_B',
'WS_wEMB11031959' : 'Section_9_C',
'WS_wEMB11031960' : 'Section_10_C',
'WS_wEMB11031961' : 'Section_11_C',
'WS_wEMB11031962' : 'Section_12_C',
'WS_wEMB11031963' : 'Section_9_D',
'WS_wEMB11031964' : 'Section_10_D',
'WS_wEMB11031965' : 'Section_11_D',
'WS_wEMB11031966' : 'Section_12_D'
}

In [ ]:
df = Embryo1_outs_comp[:]
df['Section'] = df['Sample'].map(lane_ID_dict_Embryo1)
indiv_sections = ['_a','_b','_c','_d','_A','_B','_C','_D']
for i in indiv_sections:
    df['Section'] = df['Section'].str.replace(i,'',regex=True)
df['Section_indiv'] = df['Sample'].map(lane_ID_dict_Embryo1)
Embryo1_outs_comp = df[:]

<ipython-input-19-2c151705a951>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Section'] = df['Sample'].map(lane_ID_dict_Embryo1)
<ipython-input-19-2c151705a951>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Section'] = df['Section'].str.replace(i,'',regex=True)
<ipython-input-19-2c151705a951>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Section_indiv'] = df['Sample'].map(lane_ID_dict_Embryo1)

In [ ]:
df = Embryo2_outs_comp[:]
df['Section'] = df['Sample'].map(lane_ID_dict_Embryo2)
indiv_sections = ['_a','_b','_c','_d','_A','_B','_C','_D']
for i in indiv_sections:
    df['Section'] = df['Section'].str.replace(i,'',regex=True)
df['Section_indiv'] = df['Sample'].map(lane_ID_dict_Embryo2)
Embryo2_outs_comp = df[:]

<ipython-input-20-e1dbc092c492>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Section'] = df['Sample'].map(lane_ID_dict_Embryo2)
<ipython-input-20-e1dbc092c492>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Section'] = df['Section'].str.replace(i,'',regex=True)
<ipython-input-20-e1dbc092c492>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Section_indiv'] = df['Sample'].map(lane_ID_dict_Embryo2)

In [ ]:
Embryo1_outs_comp

,Sample,n_cells,cellranger reads raw,cellbender reads filt,percent filtered,Section,Section_indiv
0,WS_wEMB10202336,2944,24531066.0,24485917.0,0.18,Section_1,Section_1_a
0,WS_wEMB10202337,11729,135642191.0,135411066.0,0.17,Section_2,Section_2_a
0,WS_wEMB10202338,10639,154649301.0,154384056.0,0.17,Section_2,Section_2_b
0,WS_wEMB10202339,10833,150333121.0,150100285.0,0.15,Section_2,Section_2_c
0,WS_wEMB10202340,9473,111161034.0,110992986.0,0.15,Section_2,Section_2_d
0,WS_wEMB10202341,10376,113730072.0,113526022.0,0.18,Section_3,Section_3_a
0,WS_wEMB10202342,11260,161623574.0,161372078.0,0.16,Section_3,Section_3_b
0,WS_wEMB10202343,10287,116396000.0,116271106.0,0.11,Section_3,Section_3_c
0,WS_wEMB10202344,10454,151689189.0,151522193.0,0.11,Section_3,Section_3_d
0,WS_wEMB10202345,7359,147640329.0,147366735.0,0.19,Section_4,Section_4_a
0,WS_wEMB10202346,6961,128183820.0,127930287.0,0.20,Section_4,Section_4_b
0,WS_wEMB10202347,7283,155107926.0,154757511.0,0.23,Section_4,Section_4_c
0,WS_wEMB10202348,9114,134310512.0,134081649.0,0.17,Section_4,Section_4_d
0,WS_wEMB10202349,7319,98991843.0,98916133.0,0.08,Section_5,Section_5_a
0,WS_wEMB10202350,7184,91569856.0,91517533.0,0.06,Section_5,Section_5_b
0,WS_wEMB10202351,7325,106786992.0,106689004.0,0.09,Section_5,Section_5_c
0,WS_wEMB10202352,7952,109779203.0,109631531.0,0.13,Section_5,Section_5_d
0,WS_wEMB10202353,7603,116835766.0,116609849.0,0.19,Section_6,Section_6_a
0,WS_wEMB10202354,7794,115402259.0,115278666.0,0.11,Section_6,Section_6_b
0,WS_wEMB10202355,8938,130777318.0,130652703.0,0.10,Section_6,Section_6_c
0,WS_wEMB10202356,7270,102262587.0,102179042.0,0.08,Section_6,Section_6_d
0,WS_wEMB10202357,8023,126119710.0,126000931.0,0.09,Section_7,Section_7_a
0,WS_wEMB10202358,7814,118752112.0,118647103.0,0.09,Section_7,Section_7_b
0,WS_wEMB10202359,7857,109405777.0,109304345.0,0.09,Section_7,Section_7_c
0,WS_wEMB10202361,7755,114820529.0,114726733.0,0.08,Section_8,Section_8_a
0,WS_wEMB10202362,7380,100459987.0,100382085.0,0.08,Section_8,Section_8_b
0,WS_wEMB10202363,7468,100471983.0,100407939.0,0.06,Section_8,Section_8_c
0,WS_wEMB10202364,7436,103914302.0,103834182.0,0.08,Section_8,Section_8_d
0,WS_wEMB10202365,11520,66391494.0,66343020.0,0.07,Section_9,Section_9_a
0,WS_wEMB10202366,6362,83605615.0,83536126.0,0.08,Section_9,Section_9_b
0,WS_wEMB10202367,6382,82617374.0,82537131.0,0.10,Section_9,Section_9_c
0,WS_wEMB10202368,6172,88666080.0,88586028.0,0.09,Section_9,Section_9_d
0,WS_wEMB10202369,7468,96747400.0,96574675.0,0.18,Section_10,Section_10_a
0,WS_wEMB10202370,7581,98745321.0,98610493.0,0.14,Section_10,Section_10_b
0,WS_wEMB10202371,7459,74788764.0,74706603.0,0.11,Section_10,Section_10_c
0,WS_wEMB10202372,6832,91709306.0,91553248.0,0.17,Section_10,Section_10_d
0,WS_wEMB10202373,7695,95579151.0,95414859.0,0.17,Section_11,Section_11_a
0,WS_wEMB10202374,9064,129227873.0,128767442.0,0.36,Section_11,Section_11_b
0,WS_wEMB10202375,7591,94623690.0,94422456.0,0.21,Section_11,Section_11_c
0,WS_wEMB10202376,7963,83940873.0,83774447.0,0.20,Section_11,Section_11_d
0,WS_wEMB10202377,7749,128047732.0,127820101.0,0.18,Section_12,Section_12_a
0,WS_wEMB10202378,8635,147186865.0,146889776.0,0.20,Section_12,Section_12_b
0,WS_wEMB10202379,7871,126227956.0,126047109.0,0.14,Section_12,Section_12_c
0,WS_wEMB10202380,7551,129458874.0,129036306.0,0.33,Section_12,Section_12_d

In [ ]:
Embryo2_outs_comp

,Sample,n_cells,cellranger reads raw,cellbender reads filt,percent filtered,Section,Section_indiv
0,WS_wEMB11031919,10485,78898874.0,78426058.0,0.60,Section_1,Section_1_A
0,WS_wEMB11031920,14251,132647383.0,131838496.0,0.61,Section_2,Section_2_A
0,WS_wEMB11031921,14285,144762897.0,143788483.0,0.67,Section_3,Section_3_A
0,WS_wEMB11031922,8822,61473767.0,61313582.0,0.26,Section_4,Section_4_A
0,WS_wEMB11031923,6408,36631735.0,36549734.0,0.22,Section_1,Section_1_B
0,WS_wEMB11031924,13570,149530533.0,148432447.0,0.73,Section_2,Section_2_B
0,WS_wEMB11031925,14439,145028334.0,144384497.0,0.44,Section_3,Section_3_B
0,WS_wEMB11031926,11173,172529852.0,171895438.0,0.37,Section_4,Section_4_B
0,WS_wEMB11031927,13019,194121078.0,193236796.0,0.46,Section_1,Section_1_C
0,WS_wEMB11031928,13744,192984367.0,192073676.0,0.47,Section_2,Section_2_C
0,WS_wEMB11031929,11393,171642426.0,170902450.0,0.43,Section_3,Section_3_C
0,WS_wEMB11031930,8806,177199774.0,176637701.0,0.32,Section_4,Section_4_C
0,WS_wEMB11031931,10296,134087378.0,133631793.0,0.34,Section_1,Section_1_D
0,WS_wEMB11031932,14109,199842479.0,198414610.0,0.71,Section_2,Section_2_D
0,WS_wEMB11031933,11385,130247251.0,129945806.0,0.23,Section_3,Section_3_D
0,WS_wEMB11031934,9128,120351954.0,119779103.0,0.48,Section_4,Section_4_D
0,WS_wEMB11031935,7103,64539855.0,64486388.0,0.08,Section_5,Section_5_A
0,WS_wEMB11031936,8304,78360270.0,78203319.0,0.20,Section_6,Section_6_A
0,WS_wEMB11031937,9497,147665857.0,147567840.0,0.07,Section_7,Section_7_A
0,WS_wEMB11031938,13417,152398107.0,151116218.0,0.84,Section_8,Section_8_A
0,WS_wEMB11031939,12813,129211049.0,128829970.0,0.29,Section_5,Section_5_B
0,WS_wEMB11031940,8982,111145337.0,110927332.0,0.20,Section_6,Section_6_B
0,WS_wEMB11031941,9551,93375343.0,93311375.0,0.07,Section_7,Section_7_B
0,WS_wEMB11031942,14981,129567832.0,128323920.0,0.96,Section_8,Section_8_B
0,WS_wEMB11031944,9611,93420135.0,93200588.0,0.24,Section_6,Section_6_C
0,WS_wEMB11031945,10848,89130108.0,88999361.0,0.15,Section_7,Section_7_C
0,WS_wEMB11031946,18126,101826698.0,101326947.0,0.49,Section_8,Section_8_C
0,WS_wEMB11031947,9540,126783530.0,126656703.0,0.10,Section_5,Section_5_D
0,WS_wEMB11031948,9086,63789993.0,63628676.0,0.25,Section_6,Section_6_D
0,WS_wEMB11031949,12303,77342394.0,77230200.0,0.15,Section_7,Section_7_D
0,WS_wEMB11031950,29557,81257774.0,81108052.0,0.18,Section_8,Section_8_D
0,WS_wEMB11031951,16252,174848015.0,174596173.0,0.14,Section_9,Section_9_A
0,WS_wEMB11031952,8999,128543336.0,128309460.0,0.18,Section_10,Section_10_A
0,WS_wEMB11031953,12459,157708702.0,157520874.0,0.12,Section_11,Section_11_A
0,WS_wEMB11031954,8160,74344534.0,74229692.0,0.15,Section_12,Section_12_A
0,WS_wEMB11031955,13083,166284277.0,165551647.0,0.44,Section_9,Section_9_B
0,WS_wEMB11031956,16909,183475725.0,182512154.0,0.53,Section_10,Section_10_B
0,WS_wEMB11031957,12191,182898337.0,182696526.0,0.11,Section_11,Section_11_B
0,WS_wEMB11031958,11801,125747084.0,125409488.0,0.27,Section_12,Section_12_B
0,WS_wEMB11031959,9003,70379399.0,69675789.0,1.00,Section_9,Section_9_C
0,WS_wEMB11031960,8771,105513137.0,105442726.0,0.07,Section_10,Section_10_C
0,WS_wEMB11031961,9788,96492851.0,96363972.0,0.13,Section_11,Section_11_C
0,WS_wEMB11031962,7621,81940732.0,81843239.0,0.12,Section_12,Section_12_C
0,WS_wEMB11031963,8166,80511815.0,79697817.0,1.01,Section_9,Section_9_D
0,WS_wEMB11031964,10177,142081744.0,141937583.0,0.10,Section_10,Section_10_D
0,WS_wEMB11031965,10020,95801936.0,95728522.0,0.08,Section_11,Section_11_D
0,WS_wEMB11031966,10099,119694690.0,119515011.0,0.15,Section_12,Section_12_D

In [ ]:
Embryo1_outs_comp.to_csv('/home/jovyan/Whole_Embryo/Generate_embryo_raw_h5ads/Embryo1_outs_comp_20220121.csv')
Embryo2_outs_comp.to_csv('/home/jovyan/Whole_Embryo/Generate_embryo_raw_h5ads/Embryo2_outs_comp_20220121.csv')

# Look at reads

In [ ]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [ ]:
Embryo1_outs_comp['no_reads_removed'] = Embryo1_outs_comp['cellranger reads raw'] - Embryo1_outs_comp['cellbender reads filt']
reads_removed_sum_E1 = Embryo1_outs_comp['no_reads_removed'].sum()
average_percentage_filtered_E1 = Embryo1_outs_comp['percent filtered'].mean()
reads_removed_sum_E1

7313237.0

In [ ]:
average_percentage_filtered_E1

0.14340909090909093

In [ ]:
Embryo1_outs_comp

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered     Section Section_indiv  no_reads_removed
0  WS_wEMB10202336     2944            24531066.0             24485917.0              0.18   Section_1   Section_1_a           45149.0
0  WS_wEMB10202337    11729           135642191.0            135411066.0              0.17   Section_2   Section_2_a          231125.0
0  WS_wEMB10202338    10639           154649301.0            154384056.0              0.17   Section_2   Section_2_b          265245.0
0  WS_wEMB10202339    10833           150333121.0            150100285.0              0.15   Section_2   Section_2_c          232836.0
0  WS_wEMB10202340     9473           111161034.0            110992986.0              0.15   Section_2   Section_2_d          168048.0
0  WS_wEMB10202341    10376           113730072.0            113526022.0              0.18   Section_3   Section_3_a          204050.0
0  WS_wEMB10202342    11260           161623574.0            161372078.0              0.16   Section_3   Section_3_b          251496.0
0  WS_wEMB10202343    10287           116396000.0            116271106.0              0.11   Section_3   Section_3_c          124894.0
0  WS_wEMB10202344    10454           151689189.0            151522193.0              0.11   Section_3   Section_3_d          166996.0
0  WS_wEMB10202345     7359           147640329.0            147366735.0              0.19   Section_4   Section_4_a          273594.0
0  WS_wEMB10202346     6961           128183820.0            127930287.0              0.20   Section_4   Section_4_b          253533.0
0  WS_wEMB10202347     7283           155107926.0            154757511.0              0.23   Section_4   Section_4_c          350415.0
0  WS_wEMB10202348     9114           134310512.0            134081649.0              0.17   Section_4   Section_4_d          228863.0
0  WS_wEMB10202349     7319            98991843.0             98916133.0              0.08   Section_5   Section_5_a           75710.0
0  WS_wEMB10202350     7184            91569856.0             91517533.0              0.06   Section_5   Section_5_b           52323.0
0  WS_wEMB10202351     7325           106786992.0            106689004.0              0.09   Section_5   Section_5_c           97988.0
0  WS_wEMB10202352     7952           109779203.0            109631531.0              0.13   Section_5   Section_5_d          147672.0
0  WS_wEMB10202353     7603           116835766.0            116609849.0              0.19   Section_6   Section_6_a          225917.0
0  WS_wEMB10202354     7794           115402259.0            115278666.0              0.11   Section_6   Section_6_b          123593.0
0  WS_wEMB10202355     8938           130777318.0            130652703.0              0.10   Section_6   Section_6_c          124615.0
0  WS_wEMB10202356     7270           102262587.0            102179042.0              0.08   Section_6   Section_6_d           83545.0
0  WS_wEMB10202357     8023           126119710.0            126000931.0              0.09   Section_7   Section_7_a          118779.0
0  WS_wEMB10202358     7814           118752112.0            118647103.0              0.09   Section_7   Section_7_b          105009.0
0  WS_wEMB10202359     7857           109405777.0            109304345.0              0.09   Section_7   Section_7_c          101432.0
0  WS_wEMB10202361     7755           114820529.0            114726733.0              0.08   Section_8   Section_8_a           93796.0
0  WS_wEMB10202362     7380           100459987.0            100382085.0              0.08   Section_8   Section_8_b           77902.0
0  WS_wEMB10202363     7468           100471983.0            100407939.0              0.06   Section_8   Section_8_c           64044.0
0  WS_wEMB10202364     7436           103914302.0            103834182.0              0.08   Section_8   Section_8_d           80120.0
0  WS_wEMB10202365    11520            66391494.0             66343020.0              0.07   Section_9   Section_9_a           48474.0
0  WS_wEMB10202366     6362            83605615.0             83536126.0              0.08   Section_9   Section_9_b           69489.0
0  WS_wEMB10202367     6382            82617374.0             82537131.0              0.10   Section_9   Section_9_c           80243.0
0  WS_wEMB10202368     6172            88666080.0             88586028.0              0.09   Section_9   Section_9_d           80052.0
0  WS_wEMB10202369     7468            96747400.0             96574675.0              0.18  Section_10  Section_10_a          172725.0
0  WS_wEMB10202370     7581            98745321.0             98610493.0              0.14  Section_10  Section_10_b          134828.0
0  WS_wEMB10202371     7459            74788764.0             74706603.0              0.11  Section_10  Section_10_c           82161.0
0  WS_wEMB10202372     6832            91709306.0             91553248.0              0.17  Section_10  Section_10_d          156058.0
0  WS_wEMB10202373     7695            95579151.0             95414859.0              0.17  Section_11  Section_11_a          164292.0
0  WS_wEMB10202374     9064           129227873.0            128767442.0              0.36  Section_11  Section_11_b          460431.0
0  WS_wEMB10202375     7591            94623690.0             94422456.0              0.21  Section_11  Section_11_c          201234.0
0  WS_wEMB10202376     7963            83940873.0             83774447.0              0.20  Section_11  Section_11_d          166426.0
0  WS_wEMB10202377     7749           128047732.0            127820101.0              0.18  Section_12  Section_12_a          227631.0
0  WS_wEMB10202378     8635           147186865.0            146889776.0              0.20  Section_12  Section_12_b          297089.0
0  WS_wEMB10202379     7871           126227956.0            126047109.0              0.14  Section_12  Section_12_c          180847.0
0  WS_wEMB10202380     7551           129458874.0            129036306.0              0.33  Section_12  Section_12_d          422568.0

In [ ]:
Embryo2_outs_comp['no_reads_removed'] = Embryo2_outs_comp['cellranger reads raw'] - Embryo2_outs_comp['cellbender reads filt']
reads_removed_sum_E2 = Embryo2_outs_comp['no_reads_removed'].sum()
average_percentage_filtered_E2 = Embryo2_outs_comp['percent filtered'].mean()
reads_removed_sum_E2

20862446.0

In [ ]:
average_percentage_filtered_E2

0.3448936170212765

In [ ]:
Embryo2_outs_comp

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered     Section Section_indiv  no_reads_removed
0  WS_wEMB11031919    10485            78898874.0             78426058.0              0.60   Section_1   Section_1_A          472816.0
0  WS_wEMB11031920    14251           132647383.0            131838496.0              0.61   Section_2   Section_2_A          808887.0
0  WS_wEMB11031921    14285           144762897.0            143788483.0              0.67   Section_3   Section_3_A          974414.0
0  WS_wEMB11031922     8822            61473767.0             61313582.0              0.26   Section_4   Section_4_A          160185.0
0  WS_wEMB11031923     6408            36631735.0             36549734.0              0.22   Section_1   Section_1_B           82001.0
0  WS_wEMB11031924    13570           149530533.0            148432447.0              0.73   Section_2   Section_2_B         1098086.0
0  WS_wEMB11031925    14439           145028334.0            144384497.0              0.44   Section_3   Section_3_B          643837.0
0  WS_wEMB11031926    11173           172529852.0            171895438.0              0.37   Section_4   Section_4_B          634414.0
0  WS_wEMB11031927    13019           194121078.0            193236796.0              0.46   Section_1   Section_1_C          884282.0
0  WS_wEMB11031928    13744           192984367.0            192073676.0              0.47   Section_2   Section_2_C          910691.0
0  WS_wEMB11031929    11393           171642426.0            170902450.0              0.43   Section_3   Section_3_C          739976.0
0  WS_wEMB11031930     8806           177199774.0            176637701.0              0.32   Section_4   Section_4_C          562073.0
0  WS_wEMB11031931    10296           134087378.0            133631793.0              0.34   Section_1   Section_1_D          455585.0
0  WS_wEMB11031932    14109           199842479.0            198414610.0              0.71   Section_2   Section_2_D         1427869.0
0  WS_wEMB11031933    11385           130247251.0            129945806.0              0.23   Section_3   Section_3_D          301445.0
0  WS_wEMB11031934     9128           120351954.0            119779103.0              0.48   Section_4   Section_4_D          572851.0
0  WS_wEMB11031935     7103            64539855.0             64486388.0              0.08   Section_5   Section_5_A           53467.0
0  WS_wEMB11031936     8304            78360270.0             78203319.0              0.20   Section_6   Section_6_A          156951.0
0  WS_wEMB11031937     9497           147665857.0            147567840.0              0.07   Section_7   Section_7_A           98017.0
0  WS_wEMB11031938    13417           152398107.0            151116218.0              0.84   Section_8   Section_8_A         1281889.0
0  WS_wEMB11031939    12813           129211049.0            128829970.0              0.29   Section_5   Section_5_B          381079.0
0  WS_wEMB11031940     8982           111145337.0            110927332.0              0.20   Section_6   Section_6_B          218005.0
0  WS_wEMB11031941     9551            93375343.0             93311375.0              0.07   Section_7   Section_7_B           63968.0
0  WS_wEMB11031942    14981           129567832.0            128323920.0              0.96   Section_8   Section_8_B         1243912.0
0  WS_wEMB11031944     9611            93420135.0             93200588.0              0.24   Section_6   Section_6_C          219547.0
0  WS_wEMB11031945    10848            89130108.0             88999361.0              0.15   Section_7   Section_7_C          130747.0
0  WS_wEMB11031946    18126           101826698.0            101326947.0              0.49   Section_8   Section_8_C          499751.0
0  WS_wEMB11031947     9540           126783530.0            126656703.0              0.10   Section_5   Section_5_D          126827.0
0  WS_wEMB11031948     9086            63789993.0             63628676.0              0.25   Section_6   Section_6_D          161317.0
0  WS_wEMB11031949    12303            77342394.0             77230200.0              0.15   Section_7   Section_7_D          112194.0
0  WS_wEMB11031950    29557            81257774.0             81108052.0              0.18   Section_8   Section_8_D          149722.0
0  WS_wEMB11031951    16252           174848015.0            174596173.0              0.14   Section_9   Section_9_A          251842.0
0  WS_wEMB11031952     8999           128543336.0            128309460.0              0.18  Section_10  Section_10_A          233876.0
0  WS_wEMB11031953    12459           157708702.0            157520874.0              0.12  Section_11  Section_11_A          187828.0
0  WS_wEMB11031954     8160            74344534.0             74229692.0              0.15  Section_12  Section_12_A          114842.0
0  WS_wEMB11031955    13083           166284277.0            165551647.0              0.44   Section_9   Section_9_B          732630.0
0  WS_wEMB11031956    16909           183475725.0            182512154.0              0.53  Section_10  Section_10_B          963571.0
0  WS_wEMB11031957    12191           182898337.0            182696526.0              0.11  Section_11  Section_11_B          201811.0
0  WS_wEMB11031958    11801           125747084.0            125409488.0              0.27  Section_12  Section_12_B          337596.0
0  WS_wEMB11031959     9003            70379399.0             69675789.0              1.00   Section_9   Section_9_C          703610.0
0  WS_wEMB11031960     8771           105513137.0            105442726.0              0.07  Section_10  Section_10_C           70411.0
0  WS_wEMB11031961     9788            96492851.0             96363972.0              0.13  Section_11  Section_11_C          128879.0
0  WS_wEMB11031962     7621            81940732.0             81843239.0              0.12  Section_12  Section_12_C           97493.0
0  WS_wEMB11031963     8166            80511815.0             79697817.0              1.01   Section_9   Section_9_D          813998.0
0  WS_wEMB11031964    10177           142081744.0            141937583.0              0.10  Section_10  Section_10_D          144161.0
0  WS_wEMB11031965    10020            95801936.0             95728522.0              0.08  Section_11  Section_11_D           73414.0
0  WS_wEMB11031966    10099           119694690.0            119515011.0              0.15  Section_12  Section_12_D          179679.0

![Embryo_sections.png](attachment:b2473238-936f-4e26-9bb2-54ccfff22359.png)

# Summarise per section

In [ ]:
data = Embryo1_outs_comp[:]
data_name = 'Embryo1_outs_comp'
col = 'Section'

for i in data[col].unique():
    print(f'{data_name} for {i}')
    print()
    df = data[data[col].isin([i])]
    n_cells = df['n_cells'].sum()
    reads_raw = df['cellranger reads raw'].sum()
    reads_filt = df['cellbender reads filt'].sum()
    percent = df['percent filtered'].mean()
    section = i
    section_indiv = 'all'
    sum_row = {'Sample':'Combined', 'n_cells':n_cells,'cellranger reads raw':reads_raw,'cellbender reads filt':reads_filt,'percent filtered':percent,'Section':section,'Section_indiv':section_indiv}
    df = df.append(sum_row, ignore_index=True)
    print(df)
    print()
    print()
    print()

Embryo1_outs_comp for Section_1

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered    Section Section_indiv
0  WS_wEMB10202336     2944            24531066.0             24485917.0              0.18  Section_1   Section_1_a
1         Combined     2944            24531066.0             24485917.0              0.18  Section_1           all



Embryo1_outs_comp for Section_2

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered    Section Section_indiv
0  WS_wEMB10202337    11729           135642191.0            135411066.0              0.17  Section_2   Section_2_a
1  WS_wEMB10202338    10639           154649301.0            154384056.0              0.17  Section_2   Section_2_b
2  WS_wEMB10202339    10833           150333121.0            150100285.0              0.15  Section_2   Section_2_c
3  WS_wEMB10202340     9473           111161034.0            110992986.0              0.15  Section_2   Section_2_d
4         Combined    42674           551785647.0            550888393.0              0.16  Section_2           all



Embryo1_outs_comp for Section_3

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered    Section Section_indiv
0  WS_wEMB10202341    10376           113730072.0            113526022.0              0.18  Section_3   Section_3_a
1  WS_wEMB10202342    11260           161623574.0            161372078.0              0.16  Section_3   Section_3_b
2  WS_wEMB10202343    10287           116396000.0            116271106.0              0.11  Section_3   Section_3_c
3  WS_wEMB10202344    10454           151689189.0            151522193.0              0.11  Section_3   Section_3_d
4         Combined    42377           543438835.0            542691399.0              0.14  Section_3           all



Embryo1_outs_comp for Section_4

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered    Section Section_indiv
0  WS_wEMB10202345     7359           147640329.0            147366735.0            0.1900  Section_4   Section_4_a
1  WS_wEMB10202346     6961           128183820.0            127930287.0            0.2000  Section_4   Section_4_b
2  WS_wEMB10202347     7283           155107926.0            154757511.0            0.2300  Section_4   Section_4_c
3  WS_wEMB10202348     9114           134310512.0            134081649.0            0.1700  Section_4   Section_4_d
4         Combined    30717           565242587.0            564136182.0            0.1975  Section_4           all



Embryo1_outs_comp for Section_5

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered    Section Section_indiv
0  WS_wEMB10202349     7319            98991843.0             98916133.0              0.08  Section_5   Section_5_a
1  WS_wEMB10202350     7184            91569856.0             91517533.0              0.06  Section_5   Section_5_b
2  WS_wEMB10202351     7325           106786992.0            106689004.0              0.09  Section_5   Section_5_c
3  WS_wEMB10202352     7952           109779203.0            109631531.0              0.13  Section_5   Section_5_d
4         Combined    29780           407127894.0            406754201.0              0.09  Section_5           all



Embryo1_outs_comp for Section_6

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered    Section Section_indiv
0  WS_wEMB10202353     7603           116835766.0            116609849.0              0.19  Section_6   Section_6_a
1  WS_wEMB10202354     7794           115402259.0            115278666.0              0.11  Section_6   Section_6_b
2  WS_wEMB10202355     8938           130777318.0            130652703.0              0.10  Section_6   Section_6_c
3  WS_wEMB10202356     7270           102262587.0            102179042.0              0.08  Section_6   Section_6_d
4         Combined    31605           465277930.0            464720260.0              0.12  Section_6           all



Embryo1_outs_comp for Section_7

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered    Section Section_indiv
0  WS_wEMB10202357     8023           126119710.0            126000931.0              0.09  Section_7   Section_7_a
1  WS_wEMB10202358     7814           118752112.0            118647103.0              0.09  Section_7   Section_7_b
2  WS_wEMB10202359     7857           109405777.0            109304345.0              0.09  Section_7   Section_7_c
3         Combined    23694           354277599.0            353952379.0              0.09  Section_7           all



Embryo1_outs_comp for Section_8

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered    Section Section_indiv
0  WS_wEMB10202361     7755           114820529.0            114726733.0             0.080  Section_8   Section_8_a
1  WS_wEMB10202362     7380           100459987.0            100382085.0             0.080  Section_8   Section_8_b
2  WS_wEMB10202363     7468           100471983.0            100407939.0             0.060  Section_8   Section_8_c
3  WS_wEMB10202364     7436           103914302.0            103834182.0             0.080  Section_8   Section_8_d
4         Combined    30039           419666801.0            419350939.0             0.075  Section_8           all



Embryo1_outs_comp for Section_9

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered    Section Section_indiv
0  WS_wEMB10202365    11520            66391494.0             66343020.0             0.070  Section_9   Section_9_a
1  WS_wEMB10202366     6362            83605615.0             83536126.0             0.080  Section_9   Section_9_b
2  WS_wEMB10202367     6382            82617374.0             82537131.0             0.100  Section_9   Section_9_c
3  WS_wEMB10202368     6172            88666080.0             88586028.0             0.090  Section_9   Section_9_d
4         Combined    30436           321280563.0            321002305.0             0.085  Section_9           all



Embryo1_outs_comp for Section_10

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered     Section Section_indiv
0  WS_wEMB10202369     7468            96747400.0             96574675.0              0.18  Section_10  Section_10_a
1  WS_wEMB10202370     7581            98745321.0             98610493.0              0.14  Section_10  Section_10_b
2  WS_wEMB10202371     7459            74788764.0             74706603.0              0.11  Section_10  Section_10_c
3  WS_wEMB10202372     6832            91709306.0             91553248.0              0.17  Section_10  Section_10_d
4         Combined    29340           361990791.0            361445019.0              0.15  Section_10           all



Embryo1_outs_comp for Section_11

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered     Section Section_indiv
0  WS_wEMB10202373     7695            95579151.0             95414859.0             0.170  Section_11  Section_11_a
1  WS_wEMB10202374     9064           129227873.0            128767442.0             0.360  Section_11  Section_11_b
2  WS_wEMB10202375     7591            94623690.0             94422456.0             0.210  Section_11  Section_11_c
3  WS_wEMB10202376     7963            83940873.0             83774447.0             0.200  Section_11  Section_11_d
4         Combined    32313           403371587.0            402379204.0             0.235  Section_11           all



Embryo1_outs_comp for Section_12

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered     Section Section_indiv
0  WS_wEMB10202377     7749           128047732.0            127820101.0            0.1800  Section_12  Section_12_a
1  WS_wEMB10202378     8635           147186865.0            146889776.0            0.2000  Section_12  Section_12_b
2  WS_wEMB10202379     7871           126227956.0            126047109.0            0.1400  Section_12  Section_12_c
3  WS_wEMB10202380     7551           129458874.0            129036306.0            0.3300  Section_12  Section_12_d
4         Combined    31806           530921427.0            529793292.0            0.2125  Section_12           all

In [ ]:
data = Embryo2_outs_comp[:]
data_name = 'Embryo2_outs_comp'
col = 'Section'

for i in data[col].unique():
    print(f'{data_name} for {i}')
    print()
    df = data[data[col].isin([i])]
    n_cells = df['n_cells'].sum()
    reads_raw = df['cellranger reads raw'].sum()
    reads_filt = df['cellbender reads filt'].sum()
    percent = df['percent filtered'].mean()
    section = i
    section_indiv = 'all'
    sum_row = {'Sample':'Combined', 'n_cells':n_cells,'cellranger reads raw':reads_raw,'cellbender reads filt':reads_filt,'percent filtered':percent,'Section':section,'Section_indiv':section_indiv}
    df = df.append(sum_row, ignore_index=True)
    print(df)
    print()
    print()
    print()

Embryo2_outs_comp for Section_1

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered    Section Section_indiv
0  WS_wEMB11031919    10485            78898874.0             78426058.0             0.600  Section_1   Section_1_A
1  WS_wEMB11031923     6408            36631735.0             36549734.0             0.220  Section_1   Section_1_B
2  WS_wEMB11031927    13019           194121078.0            193236796.0             0.460  Section_1   Section_1_C
3  WS_wEMB11031931    10296           134087378.0            133631793.0             0.340  Section_1   Section_1_D
4         Combined    40208           443739065.0            441844381.0             0.405  Section_1           all



Embryo2_outs_comp for Section_2

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered    Section Section_indiv
0  WS_wEMB11031920    14251           132647383.0            131838496.0              0.61  Section_2   Section_2_A
1  WS_wEMB11031924    13570           149530533.0            148432447.0              0.73  Section_2   Section_2_B
2  WS_wEMB11031928    13744           192984367.0            192073676.0              0.47  Section_2   Section_2_C
3  WS_wEMB11031932    14109           199842479.0            198414610.0              0.71  Section_2   Section_2_D
4         Combined    55674           675004762.0            670759229.0              0.63  Section_2           all



Embryo2_outs_comp for Section_3

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered    Section Section_indiv
0  WS_wEMB11031921    14285           144762897.0            143788483.0            0.6700  Section_3   Section_3_A
1  WS_wEMB11031925    14439           145028334.0            144384497.0            0.4400  Section_3   Section_3_B
2  WS_wEMB11031929    11393           171642426.0            170902450.0            0.4300  Section_3   Section_3_C
3  WS_wEMB11031933    11385           130247251.0            129945806.0            0.2300  Section_3   Section_3_D
4         Combined    51502           591680908.0            589021236.0            0.4425  Section_3           all



Embryo2_outs_comp for Section_4

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered    Section Section_indiv
0  WS_wEMB11031922     8822            61473767.0             61313582.0            0.2600  Section_4   Section_4_A
1  WS_wEMB11031926    11173           172529852.0            171895438.0            0.3700  Section_4   Section_4_B
2  WS_wEMB11031930     8806           177199774.0            176637701.0            0.3200  Section_4   Section_4_C
3  WS_wEMB11031934     9128           120351954.0            119779103.0            0.4800  Section_4   Section_4_D
4         Combined    37929           531555347.0            529625824.0            0.3575  Section_4           all



Embryo2_outs_comp for Section_5

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered    Section Section_indiv
0  WS_wEMB11031935     7103            64539855.0             64486388.0          0.080000  Section_5   Section_5_A
1  WS_wEMB11031939    12813           129211049.0            128829970.0          0.290000  Section_5   Section_5_B
2  WS_wEMB11031947     9540           126783530.0            126656703.0          0.100000  Section_5   Section_5_D
3         Combined    29456           320534434.0            319973061.0          0.156667  Section_5           all



Embryo2_outs_comp for Section_6

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered    Section Section_indiv
0  WS_wEMB11031936     8304            78360270.0             78203319.0            0.2000  Section_6   Section_6_A
1  WS_wEMB11031940     8982           111145337.0            110927332.0            0.2000  Section_6   Section_6_B
2  WS_wEMB11031944     9611            93420135.0             93200588.0            0.2400  Section_6   Section_6_C
3  WS_wEMB11031948     9086            63789993.0             63628676.0            0.2500  Section_6   Section_6_D
4         Combined    35983           346715735.0            345959915.0            0.2225  Section_6           all



Embryo2_outs_comp for Section_7

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered    Section Section_indiv
0  WS_wEMB11031937     9497           147665857.0            147567840.0              0.07  Section_7   Section_7_A
1  WS_wEMB11031941     9551            93375343.0             93311375.0              0.07  Section_7   Section_7_B
2  WS_wEMB11031945    10848            89130108.0             88999361.0              0.15  Section_7   Section_7_C
3  WS_wEMB11031949    12303            77342394.0             77230200.0              0.15  Section_7   Section_7_D
4         Combined    42199           407513702.0            407108776.0              0.11  Section_7           all



Embryo2_outs_comp for Section_8

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered    Section Section_indiv
0  WS_wEMB11031938    13417           152398107.0            151116218.0            0.8400  Section_8   Section_8_A
1  WS_wEMB11031942    14981           129567832.0            128323920.0            0.9600  Section_8   Section_8_B
2  WS_wEMB11031946    18126           101826698.0            101326947.0            0.4900  Section_8   Section_8_C
3  WS_wEMB11031950    29557            81257774.0             81108052.0            0.1800  Section_8   Section_8_D
4         Combined    76081           465050411.0            461875137.0            0.6175  Section_8           all



Embryo2_outs_comp for Section_9

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered    Section Section_indiv
0  WS_wEMB11031951    16252           174848015.0            174596173.0            0.1400  Section_9   Section_9_A
1  WS_wEMB11031955    13083           166284277.0            165551647.0            0.4400  Section_9   Section_9_B
2  WS_wEMB11031959     9003            70379399.0             69675789.0            1.0000  Section_9   Section_9_C
3  WS_wEMB11031963     8166            80511815.0             79697817.0            1.0100  Section_9   Section_9_D
4         Combined    46504           492023506.0            489521426.0            0.6475  Section_9           all



Embryo2_outs_comp for Section_10

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered     Section Section_indiv
0  WS_wEMB11031952     8999           128543336.0            128309460.0              0.18  Section_10  Section_10_A
1  WS_wEMB11031956    16909           183475725.0            182512154.0              0.53  Section_10  Section_10_B
2  WS_wEMB11031960     8771           105513137.0            105442726.0              0.07  Section_10  Section_10_C
3  WS_wEMB11031964    10177           142081744.0            141937583.0              0.10  Section_10  Section_10_D
4         Combined    44856           559613942.0            558201923.0              0.22  Section_10           all



Embryo2_outs_comp for Section_11

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered     Section Section_indiv
0  WS_wEMB11031953    12459           157708702.0            157520874.0              0.12  Section_11  Section_11_A
1  WS_wEMB11031957    12191           182898337.0            182696526.0              0.11  Section_11  Section_11_B
2  WS_wEMB11031961     9788            96492851.0             96363972.0              0.13  Section_11  Section_11_C
3  WS_wEMB11031965    10020            95801936.0             95728522.0              0.08  Section_11  Section_11_D
4         Combined    44458           532901826.0            532309894.0              0.11  Section_11           all



Embryo2_outs_comp for Section_12

            Sample  n_cells  cellranger reads raw  cellbender reads filt  percent filtered     Section Section_indiv
0  WS_wEMB11031954     8160            74344534.0             74229692.0            0.1500  Section_12  Section_12_A
1  WS_wEMB11031958    11801           125747084.0            125409488.0            0.2700  Section_12  Section_12_B
2  WS_wEMB11031962     7621            81940732.0             81843239.0            0.1200  Section_12  Section_12_C
3  WS_wEMB11031966    10099           119694690.0            119515011.0            0.1500  Section_12  Section_12_D
4         Combined    37681           401727040.0            400997430.0            0.1725  Section_12           all

# Repeat above for F158

In [ ]:
import numpy as np
import pandas as pd
import scanpy as sc
import os

# Set path to embryo matricies

In [ ]:
cellbender_outputs = '/nfs/team298/ar32/Whole_embryo/Cell_bender_outs/F158/F158/'

# Read in cellbender lane outs for F158

In [ ]:
adata_list1 = []
for i in list(range(5,56)):
    if i < 10:   # To account for single digit numbers
        i = '0'+str(i)
    if i in list(range(32,35)):    # to account for gap in numbering in lanes
        continue
    n = 'WS_wEMB121421'+str(i)
    
    if (n == 'WS_wEMB12142131'): # cellbender wouldn't run on this lane
        continue
    
    print(f'Loading in data: {n}')
    data = sc.read_10x_h5(cellbender_outputs + n + '/outs' + '/cellbender_out_filtered.h5')
    print('Making variable names unique')
    data.var_names_make_unique()
    data.obs['sequencing_lane_ID'] = n
    adata_list1.append(data)
    print(f'Data {n} loaded successfully. Data shape is {data.shape}')
    print("")
    del data # to try and prevent stackoverflow

Embryo3 = sc.AnnData.concatenate(*adata_list1, join = 'inner', batch_key = None, batch_categories = None, index_unique = None)
Embryo3.obs.index = Embryo3.obs.index.str.replace('-1','',regex=True)
Embryo3.obs.index = Embryo3.obs.index + '-' + Embryo3.obs['sequencing_lane_ID']
#Embryo1.var['genome'] = 'GRCh38'
print("")
print(f'Embryo3 made successfully')
print("")

Loading in data: WS_wEMB12142105

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142105 loaded successfully. Data shape is (10082, 36601)

Loading in data: WS_wEMB12142106

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142106 loaded successfully. Data shape is (11929, 36601)

Loading in data: WS_wEMB12142107

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142107 loaded successfully. Data shape is (8908, 36601)

Loading in data: WS_wEMB12142108

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142108 loaded successfully. Data shape is (7323, 36601)

Loading in data: WS_wEMB12142109

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142109 loaded successfully. Data shape is (9459, 36601)

Loading in data: WS_wEMB12142110

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142110 loaded successfully. Data shape is (12464, 36601)

Loading in data: WS_wEMB12142111

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142111 loaded successfully. Data shape is (9075, 36601)

Loading in data: WS_wEMB12142112

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142112 loaded successfully. Data shape is (8107, 36601)

Loading in data: WS_wEMB12142113

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142113 loaded successfully. Data shape is (9275, 36601)

Loading in data: WS_wEMB12142114

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142114 loaded successfully. Data shape is (12002, 36601)

Loading in data: WS_wEMB12142115

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142115 loaded successfully. Data shape is (7603, 36601)

Loading in data: WS_wEMB12142116

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142116 loaded successfully. Data shape is (7691, 36601)

Loading in data: WS_wEMB12142117

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142117 loaded successfully. Data shape is (10647, 36601)

Loading in data: WS_wEMB12142118

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142118 loaded successfully. Data shape is (10785, 36601)

Loading in data: WS_wEMB12142119

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142119 loaded successfully. Data shape is (7919, 36601)

Loading in data: WS_wEMB12142120

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142120 loaded successfully. Data shape is (9198, 36601)

Loading in data: WS_wEMB12142121

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142121 loaded successfully. Data shape is (10968, 36601)

Loading in data: WS_wEMB12142122

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142122 loaded successfully. Data shape is (10930, 36601)

Loading in data: WS_wEMB12142123

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142123 loaded successfully. Data shape is (9279, 36601)

Loading in data: WS_wEMB12142124

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142124 loaded successfully. Data shape is (6775, 36601)

Loading in data: WS_wEMB12142125

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142125 loaded successfully. Data shape is (13341, 36601)

Loading in data: WS_wEMB12142126

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142126 loaded successfully. Data shape is (9964, 36601)

Loading in data: WS_wEMB12142127

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142127 loaded successfully. Data shape is (8716, 36601)

Loading in data: WS_wEMB12142128

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142128 loaded successfully. Data shape is (7328, 36601)

Loading in data: WS_wEMB12142129

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142129 loaded successfully. Data shape is (10756, 36601)

Loading in data: WS_wEMB12142130

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142130 loaded successfully. Data shape is (9435, 36601)

Loading in data: WS_wEMB12142135

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142135 loaded successfully. Data shape is (9078, 36601)

Loading in data: WS_wEMB12142136

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142136 loaded successfully. Data shape is (10518, 36601)

Loading in data: WS_wEMB12142137

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142137 loaded successfully. Data shape is (9603, 36601)

Loading in data: WS_wEMB12142138

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142138 loaded successfully. Data shape is (9647, 36601)

Loading in data: WS_wEMB12142139

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142139 loaded successfully. Data shape is (9000, 36601)

Loading in data: WS_wEMB12142140

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142140 loaded successfully. Data shape is (9650, 36601)

Loading in data: WS_wEMB12142141

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142141 loaded successfully. Data shape is (10165, 36601)

Loading in data: WS_wEMB12142142

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142142 loaded successfully. Data shape is (6305, 36601)

Loading in data: WS_wEMB12142143

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142143 loaded successfully. Data shape is (10669, 36601)

Loading in data: WS_wEMB12142144

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142144 loaded successfully. Data shape is (9919, 36601)

Loading in data: WS_wEMB12142145

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142145 loaded successfully. Data shape is (9777, 36601)

Loading in data: WS_wEMB12142146

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142146 loaded successfully. Data shape is (10003, 36601)

Loading in data: WS_wEMB12142147

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142147 loaded successfully. Data shape is (11423, 36601)

Loading in data: WS_wEMB12142148

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142148 loaded successfully. Data shape is (18177, 36601)

Loading in data: WS_wEMB12142149

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142149 loaded successfully. Data shape is (10637, 36601)

Loading in data: WS_wEMB12142150

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142150 loaded successfully. Data shape is (8931, 36601)

Loading in data: WS_wEMB12142151

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142151 loaded successfully. Data shape is (10878, 36601)

Loading in data: WS_wEMB12142152

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142152 loaded successfully. Data shape is (9286, 36601)

Loading in data: WS_wEMB12142153

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142153 loaded successfully. Data shape is (9616, 36601)

Loading in data: WS_wEMB12142154

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142154 loaded successfully. Data shape is (8807, 36601)

Loading in data: WS_wEMB12142155

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Data WS_wEMB12142155 loaded successfully. Data shape is (11124, 36601)

Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
Observation names are not unique. To make them unique, call `.obs_names_make_unique`.

Embryo3 made successfully

In [ ]:
Embryo3.write_h5ad('/nfs/team298/ar32/Whole_embryo/Cell_bender_outs/F158/Cellbender_generated_matrix_20220801.h5ad')

... storing 'sequencing_lane_ID' as categorical
... storing 'feature_types' as categorical
... storing 'genome' as categorical

# Compare cellranger and cellbender

In [ ]:
import numpy as np
import pandas as pd
import scanpy as sc
import os

In [ ]:
Embryo3_cellbender_matricies = []

Embryo3_outs_comp = pd.DataFrame(columns=('Sample', 'n_cells', 'cellranger reads raw', 'cellbender reads filt', 'percent filtered'))

for i in list(range(5,56)):
    if i < 10:   # To account for single digit numbers
        i = '0'+str(i)
    if i in list(range(32,35)):    # to account for gap in numbering in lanes
        continue
    n = 'WS_wEMB121421'+str(i)
    
    if (n == 'WS_wEMB12142131'): # cellbender wouldn't run on this lane
        continue



    
    print(f'Starting loop for sample: {n}')
    print('Reading in cellranger raw matrix:')
    cellranger_raw = sc.read_10x_h5('/nfs/team298/ar32/Whole_embryo/Cell_ranger_outs/F158/' + n + '/raw_feature_bc_matrix.h5')
    print('Making variable names unique')
    cellranger_raw.var_names_make_unique()
    print('Cell ranger raw matrix loaded successfully')
    print()
    print('Reading in cell bender filtered matrix:')
    cellbender_filt = sc.read_10x_h5('/nfs/team298/ar32/Whole_embryo/Cell_bender_outs/F158/F158/' + n + '/outs/cellbender_out_filtered.h5')
    print('Making variable names unique')
    cellbender_filt.var_names_make_unique()
    print('Cell bender filt matrix loaded successfully')
    print()
    print('Proceeding to compare the two matricies counts values:')
    
    cellranger_raw = cellranger_raw[cellranger_raw.obs.index.isin(list(cellbender_filt.obs.index))]
    n_cells = len(cellbender_filt.obs)
    
    data = cellbender_filt
    UMI_filt = pd.DataFrame(data.X.todense())
    #UMI_filt.index = data.obs.index
    #UMI_filt.columns = data.var.index
    UMI_filt_sum = sum(UMI_filt.sum(axis=1))
    
    data = cellranger_raw
    UMI_raw = pd.DataFrame(data.X.todense())
    #UMI_raw.index = data.obs.index
    #UMI_raw.columns = data.var.index
    UMI_raw_sum = sum(UMI_raw.sum(axis=1))
    
    if (UMI_filt_sum == UMI_raw_sum):
        raise Exception('Both matricies match - not good!!!')
    
    percent_filt = round(((UMI_raw_sum-UMI_filt_sum)/UMI_raw_sum)*100,2)
    print(f'Stats for sample {n}: {n_cells} cells, {UMI_raw_sum} reads (raw), {UMI_filt_sum} reads (filt), {percent_filt}% filtered')
    table = pd.DataFrame({'Sample':[n], 'n_cells':[n_cells], 'cellranger reads raw':[UMI_raw_sum], 'cellbender reads filt':[UMI_filt_sum], 'percent filtered':[percent_filt]})
    Embryo3_outs_comp = pd.concat([Embryo3_outs_comp,table])
    print()
    print('Loop complete')
    print()
    #del cellranger_raw_
    #del cellbender_filt
    #del data
    #del UMI_raw
    #del UMI_filt

Starting loop for sample: WS_wEMB12142105
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142105: 10082 cells, 228636672.0 reads (raw), 226621997.0 reads (filt), 0.88% filtered

Loop complete

Starting loop for sample: WS_wEMB12142106
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142106: 11929 cells, 92323003.0 reads (raw), 91896197.0 reads (filt), 0.46% filtered

Loop complete

Starting loop for sample: WS_wEMB12142107
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142107: 8908 cells, 218118867.0 reads (raw), 216611807.0 reads (filt), 0.69% filtered

Loop complete

Starting loop for sample: WS_wEMB12142108
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142108: 7323 cells, 138375439.0 reads (raw), 137688440.0 reads (filt), 0.5% filtered

Loop complete

Starting loop for sample: WS_wEMB12142109
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142109: 9459 cells, 94632202.0 reads (raw), 94145411.0 reads (filt), 0.51% filtered

Loop complete

Starting loop for sample: WS_wEMB12142110
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142110: 12464 cells, 197644693.0 reads (raw), 196947220.0 reads (filt), 0.35% filtered

Loop complete

Starting loop for sample: WS_wEMB12142111
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142111: 9075 cells, 135764963.0 reads (raw), 135506384.0 reads (filt), 0.19% filtered

Loop complete

Starting loop for sample: WS_wEMB12142112
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142112: 8107 cells, 82716990.0 reads (raw), 82408247.0 reads (filt), 0.37% filtered

Loop complete

Starting loop for sample: WS_wEMB12142113
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142113: 9275 cells, 81188435.0 reads (raw), 80613776.0 reads (filt), 0.71% filtered

Loop complete

Starting loop for sample: WS_wEMB12142114
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142114: 12002 cells, 132265069.0 reads (raw), 131945744.0 reads (filt), 0.24% filtered

Loop complete

Starting loop for sample: WS_wEMB12142115
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142115: 7603 cells, 104437641.0 reads (raw), 104132328.0 reads (filt), 0.29% filtered

Loop complete

Starting loop for sample: WS_wEMB12142116
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142116: 7691 cells, 74439099.0 reads (raw), 74267097.0 reads (filt), 0.23% filtered

Loop complete

Starting loop for sample: WS_wEMB12142117
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142117: 10647 cells, 90566918.0 reads (raw), 90182737.0 reads (filt), 0.42% filtered

Loop complete

Starting loop for sample: WS_wEMB12142118
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142118: 10785 cells, 106808047.0 reads (raw), 106541383.0 reads (filt), 0.25% filtered

Loop complete

Starting loop for sample: WS_wEMB12142119
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142119: 7919 cells, 103440951.0 reads (raw), 103183288.0 reads (filt), 0.25% filtered

Loop complete

Starting loop for sample: WS_wEMB12142120
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142120: 9198 cells, 142426265.0 reads (raw), 141908996.0 reads (filt), 0.36% filtered

Loop complete

Starting loop for sample: WS_wEMB12142121
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142121: 10968 cells, 67731292.0 reads (raw), 67483388.0 reads (filt), 0.37% filtered

Loop complete

Starting loop for sample: WS_wEMB12142122
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142122: 10930 cells, 50359057.0 reads (raw), 50218508.0 reads (filt), 0.28% filtered

Loop complete

Starting loop for sample: WS_wEMB12142123
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142123: 9279 cells, 48721551.0 reads (raw), 48588280.0 reads (filt), 0.27% filtered

Loop complete

Starting loop for sample: WS_wEMB12142124
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142124: 6775 cells, 106825760.0 reads (raw), 106376176.0 reads (filt), 0.42% filtered

Loop complete

Starting loop for sample: WS_wEMB12142125
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142125: 13341 cells, 111699195.0 reads (raw), 110922450.0 reads (filt), 0.7% filtered

Loop complete

Starting loop for sample: WS_wEMB12142126
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142126: 9964 cells, 142452081.0 reads (raw), 142030538.0 reads (filt), 0.3% filtered

Loop complete

Starting loop for sample: WS_wEMB12142127
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142127: 8716 cells, 68038908.0 reads (raw), 67876282.0 reads (filt), 0.24% filtered

Loop complete

Starting loop for sample: WS_wEMB12142128
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142128: 7328 cells, 28113047.0 reads (raw), 28054395.0 reads (filt), 0.21% filtered

Loop complete

Starting loop for sample: WS_wEMB12142129
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142129: 10756 cells, 86585786.0 reads (raw), 86339220.0 reads (filt), 0.28% filtered

Loop complete

Starting loop for sample: WS_wEMB12142130
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142130: 9435 cells, 66898699.0 reads (raw), 66681240.0 reads (filt), 0.33% filtered

Loop complete

Starting loop for sample: WS_wEMB12142135
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142135: 9078 cells, 105556647.0 reads (raw), 105230816.0 reads (filt), 0.31% filtered

Loop complete

Starting loop for sample: WS_wEMB12142136
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142136: 10518 cells, 130988912.0 reads (raw), 130482344.0 reads (filt), 0.39% filtered

Loop complete

Starting loop for sample: WS_wEMB12142137
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142137: 9603 cells, 107003844.0 reads (raw), 106839256.0 reads (filt), 0.15% filtered

Loop complete

Starting loop for sample: WS_wEMB12142138
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142138: 9647 cells, 122639569.0 reads (raw), 122310843.0 reads (filt), 0.27% filtered

Loop complete

Starting loop for sample: WS_wEMB12142139
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142139: 9000 cells, 93680511.0 reads (raw), 93440365.0 reads (filt), 0.26% filtered

Loop complete

Starting loop for sample: WS_wEMB12142140
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142140: 9650 cells, 73620186.0 reads (raw), 73389870.0 reads (filt), 0.31% filtered

Loop complete

Starting loop for sample: WS_wEMB12142141
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142141: 10165 cells, 133212913.0 reads (raw), 132660803.0 reads (filt), 0.41% filtered

Loop complete

Starting loop for sample: WS_wEMB12142142
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142142: 6305 cells, 54277130.0 reads (raw), 54023264.0 reads (filt), 0.47% filtered

Loop complete

Starting loop for sample: WS_wEMB12142143
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142143: 10669 cells, 100005950.0 reads (raw), 99579444.0 reads (filt), 0.43% filtered

Loop complete

Starting loop for sample: WS_wEMB12142144
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142144: 9919 cells, 94200210.0 reads (raw), 94048696.0 reads (filt), 0.16% filtered

Loop complete

Starting loop for sample: WS_wEMB12142145
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142145: 9777 cells, 115073138.0 reads (raw), 114845662.0 reads (filt), 0.2% filtered

Loop complete

Starting loop for sample: WS_wEMB12142146
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142146: 10003 cells, 106404266.0 reads (raw), 106036265.0 reads (filt), 0.35% filtered

Loop complete

Starting loop for sample: WS_wEMB12142147
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142147: 11423 cells, 152773167.0 reads (raw), 151945159.0 reads (filt), 0.54% filtered

Loop complete

Starting loop for sample: WS_wEMB12142148
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142148: 18177 cells, 128555010.0 reads (raw), 127899702.0 reads (filt), 0.51% filtered

Loop complete

Starting loop for sample: WS_wEMB12142149
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142149: 10637 cells, 120137049.0 reads (raw), 119837797.0 reads (filt), 0.25% filtered

Loop complete

Starting loop for sample: WS_wEMB12142150
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142150: 8931 cells, 100812652.0 reads (raw), 100229730.0 reads (filt), 0.58% filtered

Loop complete

Starting loop for sample: WS_wEMB12142151
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142151: 10878 cells, 97507505.0 reads (raw), 96967520.0 reads (filt), 0.55% filtered

Loop complete

Starting loop for sample: WS_wEMB12142152
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142152: 9286 cells, 34715940.0 reads (raw), 34627870.0 reads (filt), 0.25% filtered

Loop complete

Starting loop for sample: WS_wEMB12142153
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142153: 9616 cells, 102982066.0 reads (raw), 102654291.0 reads (filt), 0.32% filtered

Loop complete

Starting loop for sample: WS_wEMB12142154
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142154: 8807 cells, 108174566.0 reads (raw), 107705635.0 reads (filt), 0.43% filtered

Loop complete

Starting loop for sample: WS_wEMB12142155
Reading in cellranger raw matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell ranger raw matrix loaded successfully

Reading in cell bender filtered matrix:

Variable names are not unique. To make them unique, call `.var_names_make_unique`.
Variable names are not unique. To make them unique, call `.var_names_make_unique`.

Making variable names unique
Cell bender filt matrix loaded successfully

Proceeding to compare the two matricies counts values:
Stats for sample WS_wEMB12142155: 11124 cells, 119229762.0 reads (raw), 118637396.0 reads (filt), 0.5% filtered

Loop complete

# Observe output

In [ ]:
Embryo3_outs_comp

,Sample,n_cells,cellranger reads raw,cellbender reads filt,percent filtered
0,WS_wEMB12142105,10082,228636672.0,226621997.0,0.88
0,WS_wEMB12142106,11929,92323003.0,91896197.0,0.46
0,WS_wEMB12142107,8908,218118867.0,216611807.0,0.69
0,WS_wEMB12142108,7323,138375439.0,137688440.0,0.50
0,WS_wEMB12142109,9459,94632202.0,94145411.0,0.51
0,WS_wEMB12142110,12464,197644693.0,196947220.0,0.35
0,WS_wEMB12142111,9075,135764963.0,135506384.0,0.19
0,WS_wEMB12142112,8107,82716990.0,82408247.0,0.37
0,WS_wEMB12142113,9275,81188435.0,80613776.0,0.71
0,WS_wEMB12142114,12002,132265069.0,131945744.0,0.24
0,WS_wEMB12142115,7603,104437641.0,104132328.0,0.29
0,WS_wEMB12142116,7691,74439099.0,74267097.0,0.23
0,WS_wEMB12142117,10647,90566918.0,90182737.0,0.42
0,WS_wEMB12142118,10785,106808047.0,106541383.0,0.25
0,WS_wEMB12142119,7919,103440951.0,103183288.0,0.25
0,WS_wEMB12142120,9198,142426265.0,141908996.0,0.36
0,WS_wEMB12142121,10968,67731292.0,67483388.0,0.37
0,WS_wEMB12142122,10930,50359057.0,50218508.0,0.28
0,WS_wEMB12142123,9279,48721551.0,48588280.0,0.27
0,WS_wEMB12142124,6775,106825760.0,106376176.0,0.42
0,WS_wEMB12142125,13341,111699195.0,110922450.0,0.70
0,WS_wEMB12142126,9964,142452081.0,142030538.0,0.30
0,WS_wEMB12142127,8716,68038908.0,67876282.0,0.24
0,WS_wEMB12142128,7328,28113047.0,28054395.0,0.21
0,WS_wEMB12142129,10756,86585786.0,86339220.0,0.28
0,WS_wEMB12142130,9435,66898699.0,66681240.0,0.33
0,WS_wEMB12142135,9078,105556647.0,105230816.0,0.31
0,WS_wEMB12142136,10518,130988912.0,130482344.0,0.39
0,WS_wEMB12142137,9603,107003844.0,106839256.0,0.15
0,WS_wEMB12142138,9647,122639569.0,122310843.0,0.27
0,WS_wEMB12142139,9000,93680511.0,93440365.0,0.26
0,WS_wEMB12142140,9650,73620186.0,73389870.0,0.31
0,WS_wEMB12142141,10165,133212913.0,132660803.0,0.41
0,WS_wEMB12142142,6305,54277130.0,54023264.0,0.47
0,WS_wEMB12142143,10669,100005950.0,99579444.0,0.43
0,WS_wEMB12142144,9919,94200210.0,94048696.0,0.16
0,WS_wEMB12142145,9777,115073138.0,114845662.0,0.20
0,WS_wEMB12142146,10003,106404266.0,106036265.0,0.35
0,WS_wEMB12142147,11423,152773167.0,151945159.0,0.54
0,WS_wEMB12142148,18177,128555010.0,127899702.0,0.51
0,WS_wEMB12142149,10637,120137049.0,119837797.0,0.25
0,WS_wEMB12142150,8931,100812652.0,100229730.0,0.58
0,WS_wEMB12142151,10878,97507505.0,96967520.0,0.55
0,WS_wEMB12142152,9286,34715940.0,34627870.0,0.25
0,WS_wEMB12142153,9616,102982066.0,102654291.0,0.32
0,WS_wEMB12142154,8807,108174566.0,107705635.0,0.43
0,WS_wEMB12142155,11124,119229762.0,118637396.0,0.50

# Add in section metadata

In [ ]:
lane_ID_dict_Embryo3 = {
    
'WS_wEMB12142105' : 'Section_01_a',
'WS_wEMB12142106' : 'Section_02_a',
'WS_wEMB12142107' : 'Section_03_a',
'WS_wEMB12142108' : 'Section_04_a',
'WS_wEMB12142109' : 'Section_01_b',
'WS_wEMB12142110' : 'Section_02_b',
'WS_wEMB12142111' : 'Section_03_b',
'WS_wEMB12142112' : 'Section_04_b',
'WS_wEMB12142113' : 'Section_01_c',
'WS_wEMB12142114' : 'Section_02_c',
'WS_wEMB12142115' : 'Section_03_c',
'WS_wEMB12142116' : 'Section_04_c',
'WS_wEMB12142117' : 'Section_01_d',
'WS_wEMB12142118' : 'Section_02_d',
'WS_wEMB12142119' : 'Section_03_d',
'WS_wEMB12142120' : 'Section_04_d',
'WS_wEMB12142121' : 'Section_05_a',
'WS_wEMB12142122' : 'Section_06_a',
'WS_wEMB12142123' : 'Section_07_a',
'WS_wEMB12142124' : 'Section_08_a',
'WS_wEMB12142125' : 'Section_05_b',
'WS_wEMB12142126' : 'Section_06_b',
'WS_wEMB12142127' : 'Section_07_b',
'WS_wEMB12142128' : 'Section_08_b',
'WS_wEMB12142129' : 'Section_05_c',
'WS_wEMB12142130' : 'Section_06_c',
'WS_wEMB12142131' : 'Section_07_c',
'WS_wEMB12142135' : 'Section_08_c',
'WS_wEMB12142136' : 'Section_05_d',
'WS_wEMB12142137' : 'Section_06_d',
'WS_wEMB12142138' : 'Section_07_d',
'WS_wEMB12142139' : 'Section_08_d',
'WS_wEMB12142140' : 'Section_09_a',
'WS_wEMB12142141' : 'Section_10_a',
'WS_wEMB12142142' : 'Section_11_a',
'WS_wEMB12142143' : 'Section_12_a',
'WS_wEMB12142144' : 'Section_09_b',
'WS_wEMB12142145' : 'Section_10_b',
'WS_wEMB12142146' : 'Section_11_b',
'WS_wEMB12142147' : 'Section_12_b',
'WS_wEMB12142148' : 'Section_09_c',
'WS_wEMB12142149' : 'Section_10_c',
'WS_wEMB12142150' : 'Section_11_c',
'WS_wEMB12142151' : 'Section_12_c',
'WS_wEMB12142152' : 'Section_09_d',
'WS_wEMB12142153' : 'Section_10_d',
'WS_wEMB12142154' : 'Section_11_d',
'WS_wEMB12142155' : 'Section_12_d',
}

In [ ]:
df = Embryo3_outs_comp[:]
df['Section'] = df['Sample'].map(lane_ID_dict_Embryo3)
indiv_sections = ['_a','_b','_c','_d','_A','_B','_C','_D']
for i in indiv_sections:
    df['Section'] = df['Section'].str.replace(i,'',regex=True)
df['Section_indiv'] = df['Sample'].map(lane_ID_dict_Embryo3)
Embryo3_outs_comp = df[:]

<ipython-input-13-d4467369cbdb>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Section'] = df['Sample'].map(lane_ID_dict_Embryo3)
<ipython-input-13-d4467369cbdb>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Section'] = df['Section'].str.replace(i,'',regex=True)
<ipython-input-13-d4467369cbdb>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Section_indiv'] = df['Sample'].map(lane_ID_dict_Embryo3)

In [ ]:
Embryo3_outs_comp

,Sample,n_cells,cellranger reads raw,cellbender reads filt,percent filtered,Section,Section_indiv
0,WS_wEMB12142105,10082,228636672.0,226621997.0,0.88,Section_01,Section_01_a
0,WS_wEMB12142106,11929,92323003.0,91896197.0,0.46,Section_02,Section_02_a
0,WS_wEMB12142107,8908,218118867.0,216611807.0,0.69,Section_03,Section_03_a
0,WS_wEMB12142108,7323,138375439.0,137688440.0,0.50,Section_04,Section_04_a
0,WS_wEMB12142109,9459,94632202.0,94145411.0,0.51,Section_01,Section_01_b
0,WS_wEMB12142110,12464,197644693.0,196947220.0,0.35,Section_02,Section_02_b
0,WS_wEMB12142111,9075,135764963.0,135506384.0,0.19,Section_03,Section_03_b
0,WS_wEMB12142112,8107,82716990.0,82408247.0,0.37,Section_04,Section_04_b
0,WS_wEMB12142113,9275,81188435.0,80613776.0,0.71,Section_01,Section_01_c
0,WS_wEMB12142114,12002,132265069.0,131945744.0,0.24,Section_02,Section_02_c
0,WS_wEMB12142115,7603,104437641.0,104132328.0,0.29,Section_03,Section_03_c
0,WS_wEMB12142116,7691,74439099.0,74267097.0,0.23,Section_04,Section_04_c
0,WS_wEMB12142117,10647,90566918.0,90182737.0,0.42,Section_01,Section_01_d
0,WS_wEMB12142118,10785,106808047.0,106541383.0,0.25,Section_02,Section_02_d
0,WS_wEMB12142119,7919,103440951.0,103183288.0,0.25,Section_03,Section_03_d
0,WS_wEMB12142120,9198,142426265.0,141908996.0,0.36,Section_04,Section_04_d
0,WS_wEMB12142121,10968,67731292.0,67483388.0,0.37,Section_05,Section_05_a
0,WS_wEMB12142122,10930,50359057.0,50218508.0,0.28,Section_06,Section_06_a
0,WS_wEMB12142123,9279,48721551.0,48588280.0,0.27,Section_07,Section_07_a
0,WS_wEMB12142124,6775,106825760.0,106376176.0,0.42,Section_08,Section_08_a
0,WS_wEMB12142125,13341,111699195.0,110922450.0,0.70,Section_05,Section_05_b
0,WS_wEMB12142126,9964,142452081.0,142030538.0,0.30,Section_06,Section_06_b
0,WS_wEMB12142127,8716,68038908.0,67876282.0,0.24,Section_07,Section_07_b
0,WS_wEMB12142128,7328,28113047.0,28054395.0,0.21,Section_08,Section_08_b
0,WS_wEMB12142129,10756,86585786.0,86339220.0,0.28,Section_05,Section_05_c
0,WS_wEMB12142130,9435,66898699.0,66681240.0,0.33,Section_06,Section_06_c
0,WS_wEMB12142135,9078,105556647.0,105230816.0,0.31,Section_08,Section_08_c
0,WS_wEMB12142136,10518,130988912.0,130482344.0,0.39,Section_05,Section_05_d
0,WS_wEMB12142137,9603,107003844.0,106839256.0,0.15,Section_06,Section_06_d
0,WS_wEMB12142138,9647,122639569.0,122310843.0,0.27,Section_07,Section_07_d
0,WS_wEMB12142139,9000,93680511.0,93440365.0,0.26,Section_08,Section_08_d
0,WS_wEMB12142140,9650,73620186.0,73389870.0,0.31,Section_09,Section_09_a
0,WS_wEMB12142141,10165,133212913.0,132660803.0,0.41,Section_10,Section_10_a
0,WS_wEMB12142142,6305,54277130.0,54023264.0,0.47,Section_11,Section_11_a
0,WS_wEMB12142143,10669,100005950.0,99579444.0,0.43,Section_12,Section_12_a
0,WS_wEMB12142144,9919,94200210.0,94048696.0,0.16,Section_09,Section_09_b
0,WS_wEMB12142145,9777,115073138.0,114845662.0,0.20,Section_10,Section_10_b
0,WS_wEMB12142146,10003,106404266.0,106036265.0,0.35,Section_11,Section_11_b
0,WS_wEMB12142147,11423,152773167.0,151945159.0,0.54,Section_12,Section_12_b
0,WS_wEMB12142148,18177,128555010.0,127899702.0,0.51,Section_09,Section_09_c
0,WS_wEMB12142149,10637,120137049.0,119837797.0,0.25,Section_10,Section_10_c
0,WS_wEMB12142150,8931,100812652.0,100229730.0,0.58,Section_11,Section_11_c
0,WS_wEMB12142151,10878,97507505.0,96967520.0,0.55,Section_12,Section_12_c
0,WS_wEMB12142152,9286,34715940.0,34627870.0,0.25,Section_09,Section_09_d
0,WS_wEMB12142153,9616,102982066.0,102654291.0,0.32,Section_10,Section_10_d
0,WS_wEMB12142154,8807,108174566.0,107705635.0,0.43,Section_11,Section_11_d
0,WS_wEMB12142155,11124,119229762.0,118637396.0,0.50,Section_12,Section_12_d

In [ ]:
Embryo3_outs_comp.to_csv('/home/jovyan/Whole_Embryo/Generate_embryo_raw_h5ads/Embryo3_outs_comp_20220802.csv')

# check reads

In [ ]:
Embryo3_outs_comp['no_reads_removed'] = Embryo3_outs_comp['cellranger reads raw'] - Embryo3_outs_comp['cellbender reads filt']
reads_removed_sum_E3 = Embryo3_outs_comp['no_reads_removed'].sum()
average_percentage_filtered_E3 = Embryo3_outs_comp['percent filtered'].mean()
reads_removed_sum_E3

<ipython-input-21-f2e1178dadc5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Embryo3_outs_comp['no_reads_removed'] = Embryo3_outs_comp['cellranger reads raw'] - Embryo3_outs_comp['cellbender reads filt']

20197366.0

In [ ]:
average_percentage_filtered_E3

0.37744680851063833

In [ ]:
Embryo3_outs_comp

            Sample n_cells  cellranger reads raw  cellbender reads filt  percent filtered     Section Section_indiv  no_reads_removed
0  WS_wEMB12142105   10082           228636672.0            226621997.0              0.88  Section_01  Section_01_a         2014675.0
0  WS_wEMB12142106   11929            92323003.0             91896197.0              0.46  Section_02  Section_02_a          426806.0
0  WS_wEMB12142107    8908           218118867.0            216611807.0              0.69  Section_03  Section_03_a         1507060.0
0  WS_wEMB12142108    7323           138375439.0            137688440.0              0.50  Section_04  Section_04_a          686999.0
0  WS_wEMB12142109    9459            94632202.0             94145411.0              0.51  Section_01  Section_01_b          486791.0
0  WS_wEMB12142110   12464           197644693.0            196947220.0              0.35  Section_02  Section_02_b          697473.0
0  WS_wEMB12142111    9075           135764963.0            135506384.0              0.19  Section_03  Section_03_b          258579.0
0  WS_wEMB12142112    8107            82716990.0             82408247.0              0.37  Section_04  Section_04_b          308743.0
0  WS_wEMB12142113    9275            81188435.0             80613776.0              0.71  Section_01  Section_01_c          574659.0
0  WS_wEMB12142114   12002           132265069.0            131945744.0              0.24  Section_02  Section_02_c          319325.0
0  WS_wEMB12142115    7603           104437641.0            104132328.0              0.29  Section_03  Section_03_c          305313.0
0  WS_wEMB12142116    7691            74439099.0             74267097.0              0.23  Section_04  Section_04_c          172002.0
0  WS_wEMB12142117   10647            90566918.0             90182737.0              0.42  Section_01  Section_01_d          384181.0
0  WS_wEMB12142118   10785           106808047.0            106541383.0              0.25  Section_02  Section_02_d          266664.0
0  WS_wEMB12142119    7919           103440951.0            103183288.0              0.25  Section_03  Section_03_d          257663.0
0  WS_wEMB12142120    9198           142426265.0            141908996.0              0.36  Section_04  Section_04_d          517269.0
0  WS_wEMB12142121   10968            67731292.0             67483388.0              0.37  Section_05  Section_05_a          247904.0
0  WS_wEMB12142122   10930            50359057.0             50218508.0              0.28  Section_06  Section_06_a          140549.0
0  WS_wEMB12142123    9279            48721551.0             48588280.0              0.27  Section_07  Section_07_a          133271.0
0  WS_wEMB12142124    6775           106825760.0            106376176.0              0.42  Section_08  Section_08_a          449584.0
0  WS_wEMB12142125   13341           111699195.0            110922450.0              0.70  Section_05  Section_05_b          776745.0
0  WS_wEMB12142126    9964           142452081.0            142030538.0              0.30  Section_06  Section_06_b          421543.0
0  WS_wEMB12142127    8716            68038908.0             67876282.0              0.24  Section_07  Section_07_b          162626.0
0  WS_wEMB12142128    7328            28113047.0             28054395.0              0.21  Section_08  Section_08_b           58652.0
0  WS_wEMB12142129   10756            86585786.0             86339220.0              0.28  Section_05  Section_05_c          246566.0
0  WS_wEMB12142130    9435            66898699.0             66681240.0              0.33  Section_06  Section_06_c          217459.0
0  WS_wEMB12142135    9078           105556647.0            105230816.0              0.31  Section_08  Section_08_c          325831.0
0  WS_wEMB12142136   10518           130988912.0            130482344.0              0.39  Section_05  Section_05_d          506568.0
0  WS_wEMB12142137    9603           107003844.0            106839256.0              0.15  Section_06  Section_06_d          164588.0
0  WS_wEMB12142138    9647           122639569.0            122310843.0              0.27  Section_07  Section_07_d          328726.0
0  WS_wEMB12142139    9000            93680511.0             93440365.0              0.26  Section_08  Section_08_d          240146.0
0  WS_wEMB12142140    9650            73620186.0             73389870.0              0.31  Section_09  Section_09_a          230316.0
0  WS_wEMB12142141   10165           133212913.0            132660803.0              0.41  Section_10  Section_10_a          552110.0
0  WS_wEMB12142142    6305            54277130.0             54023264.0              0.47  Section_11  Section_11_a          253866.0
0  WS_wEMB12142143   10669           100005950.0             99579444.0              0.43  Section_12  Section_12_a          426506.0
0  WS_wEMB12142144    9919            94200210.0             94048696.0              0.16  Section_09  Section_09_b          151514.0
0  WS_wEMB12142145    9777           115073138.0            114845662.0              0.20  Section_10  Section_10_b          227476.0
0  WS_wEMB12142146   10003           106404266.0            106036265.0              0.35  Section_11  Section_11_b          368001.0
0  WS_wEMB12142147   11423           152773167.0            151945159.0              0.54  Section_12  Section_12_b          828008.0
0  WS_wEMB12142148   18177           128555010.0            127899702.0              0.51  Section_09  Section_09_c          655308.0
0  WS_wEMB12142149   10637           120137049.0            119837797.0              0.25  Section_10  Section_10_c          299252.0
0  WS_wEMB12142150    8931           100812652.0            100229730.0              0.58  Section_11  Section_11_c          582922.0
0  WS_wEMB12142151   10878            97507505.0             96967520.0              0.55  Section_12  Section_12_c          539985.0
0  WS_wEMB12142152    9286            34715940.0             34627870.0              0.25  Section_09  Section_09_d           88070.0
0  WS_wEMB12142153    9616           102982066.0            102654291.0              0.32  Section_10  Section_10_d          327775.0
0  WS_wEMB12142154    8807           108174566.0            107705635.0              0.43  Section_11  Section_11_d          468931.0
0  WS_wEMB12142155   11124           119229762.0            118637396.0              0.50  Section_12  Section_12_d          592366.0

In [ ]:
Embryo3_outs_comp['percent filtered'].mean()

0.37744680851063833

# summarise per section

In [ ]:
data = Embryo3_outs_comp[:]
data_name = 'Embryo3_outs_comp'
col = 'Section'

for i in data[col].unique():
    print(f'{data_name} for {i}')
    print()
    df = data[data[col].isin([i])]
    n_cells = df['n_cells'].sum()
    reads_raw = df['cellranger reads raw'].sum()
    reads_filt = df['cellbender reads filt'].sum()
    percent = df['percent filtered'].mean()
    section = i
    section_indiv = 'all'
    no_reads_removed = df['no_reads_removed'].sum()
    sum_row = {'Sample':'Combined', 'n_cells':n_cells,'cellranger reads raw':reads_raw,'cellbender reads filt':reads_filt,'percent filtered':percent,'Section':section,'Section_indiv':section_indiv,'no_reads_removed':no_reads_removed}
    df = df.append(sum_row, ignore_index=True)
    print(df)
    print()
    print()
    print()

Embryo3_outs_comp for Section_01

            Sample n_cells  cellranger reads raw  cellbender reads filt  percent filtered     Section Section_indiv  no_reads_removed
0  WS_wEMB12142105   10082           228636672.0            226621997.0              0.88  Section_01  Section_01_a         2014675.0
1  WS_wEMB12142109    9459            94632202.0             94145411.0              0.51  Section_01  Section_01_b          486791.0
2  WS_wEMB12142113    9275            81188435.0             80613776.0              0.71  Section_01  Section_01_c          574659.0
3  WS_wEMB12142117   10647            90566918.0             90182737.0              0.42  Section_01  Section_01_d          384181.0
4         Combined   39463           495024227.0            491563921.0              0.63  Section_01           all         3460306.0



Embryo3_outs_comp for Section_02

            Sample n_cells  cellranger reads raw  cellbender reads filt  percent filtered     Section Section_indiv  no_reads_removed
0  WS_wEMB12142106   11929            92323003.0             91896197.0             0.460  Section_02  Section_02_a          426806.0
1  WS_wEMB12142110   12464           197644693.0            196947220.0             0.350  Section_02  Section_02_b          697473.0
2  WS_wEMB12142114   12002           132265069.0            131945744.0             0.240  Section_02  Section_02_c          319325.0
3  WS_wEMB12142118   10785           106808047.0            106541383.0             0.250  Section_02  Section_02_d          266664.0
4         Combined   47180           529040812.0            527330544.0             0.325  Section_02           all         1710268.0



Embryo3_outs_comp for Section_03

            Sample n_cells  cellranger reads raw  cellbender reads filt  percent filtered     Section Section_indiv  no_reads_removed
0  WS_wEMB12142107    8908           218118867.0            216611807.0             0.690  Section_03  Section_03_a         1507060.0
1  WS_wEMB12142111    9075           135764963.0            135506384.0             0.190  Section_03  Section_03_b          258579.0
2  WS_wEMB12142115    7603           104437641.0            104132328.0             0.290  Section_03  Section_03_c          305313.0
3  WS_wEMB12142119    7919           103440951.0            103183288.0             0.250  Section_03  Section_03_d          257663.0
4         Combined   33505           561762422.0            559433807.0             0.355  Section_03           all         2328615.0



Embryo3_outs_comp for Section_04

            Sample n_cells  cellranger reads raw  cellbender reads filt  percent filtered     Section Section_indiv  no_reads_removed
0  WS_wEMB12142108    7323           138375439.0            137688440.0             0.500  Section_04  Section_04_a          686999.0
1  WS_wEMB12142112    8107            82716990.0             82408247.0             0.370  Section_04  Section_04_b          308743.0
2  WS_wEMB12142116    7691            74439099.0             74267097.0             0.230  Section_04  Section_04_c          172002.0
3  WS_wEMB12142120    9198           142426265.0            141908996.0             0.360  Section_04  Section_04_d          517269.0
4         Combined   32319           437957793.0            436272780.0             0.365  Section_04           all         1685013.0



Embryo3_outs_comp for Section_05

            Sample n_cells  cellranger reads raw  cellbender reads filt  percent filtered     Section Section_indiv  no_reads_removed
0  WS_wEMB12142121   10968            67731292.0             67483388.0             0.370  Section_05  Section_05_a          247904.0
1  WS_wEMB12142125   13341           111699195.0            110922450.0             0.700  Section_05  Section_05_b          776745.0
2  WS_wEMB12142129   10756            86585786.0             86339220.0             0.280  Section_05  Section_05_c          246566.0
3  WS_wEMB12142136   10518           130988912.0            130482344.0             0.390  Section_05  Section_05_d          506568.0
4         Combined   45583           397005185.0            395227402.0             0.435  Section_05           all         1777783.0



Embryo3_outs_comp for Section_06

            Sample n_cells  cellranger reads raw  cellbender reads filt  percent filtered     Section Section_indiv  no_reads_removed
0  WS_wEMB12142122   10930            50359057.0             50218508.0             0.280  Section_06  Section_06_a          140549.0
1  WS_wEMB12142126    9964           142452081.0            142030538.0             0.300  Section_06  Section_06_b          421543.0
2  WS_wEMB12142130    9435            66898699.0             66681240.0             0.330  Section_06  Section_06_c          217459.0
3  WS_wEMB12142137    9603           107003844.0            106839256.0             0.150  Section_06  Section_06_d          164588.0
4         Combined   39932           366713681.0            365769542.0             0.265  Section_06           all          944139.0



Embryo3_outs_comp for Section_07

            Sample n_cells  cellranger reads raw  cellbender reads filt  percent filtered     Section Section_indiv  no_reads_removed
0  WS_wEMB12142123    9279            48721551.0             48588280.0              0.27  Section_07  Section_07_a          133271.0
1  WS_wEMB12142127    8716            68038908.0             67876282.0              0.24  Section_07  Section_07_b          162626.0
2  WS_wEMB12142138    9647           122639569.0            122310843.0              0.27  Section_07  Section_07_d          328726.0
3         Combined   27642           239400028.0            238775405.0              0.26  Section_07           all          624623.0



Embryo3_outs_comp for Section_08

            Sample n_cells  cellranger reads raw  cellbender reads filt  percent filtered     Section Section_indiv  no_reads_removed
0  WS_wEMB12142124    6775           106825760.0            106376176.0              0.42  Section_08  Section_08_a          449584.0
1  WS_wEMB12142128    7328            28113047.0             28054395.0              0.21  Section_08  Section_08_b           58652.0
2  WS_wEMB12142135    9078           105556647.0            105230816.0              0.31  Section_08  Section_08_c          325831.0
3  WS_wEMB12142139    9000            93680511.0             93440365.0              0.26  Section_08  Section_08_d          240146.0
4         Combined   32181           334175965.0            333101752.0              0.30  Section_08           all         1074213.0



Embryo3_outs_comp for Section_09

            Sample n_cells  cellranger reads raw  cellbender reads filt  percent filtered     Section Section_indiv  no_reads_removed
0  WS_wEMB12142140    9650            73620186.0             73389870.0            0.3100  Section_09  Section_09_a          230316.0
1  WS_wEMB12142144    9919            94200210.0             94048696.0            0.1600  Section_09  Section_09_b          151514.0
2  WS_wEMB12142148   18177           128555010.0            127899702.0            0.5100  Section_09  Section_09_c          655308.0
3  WS_wEMB12142152    9286            34715940.0             34627870.0            0.2500  Section_09  Section_09_d           88070.0
4         Combined   47032           331091346.0            329966138.0            0.3075  Section_09           all         1125208.0



Embryo3_outs_comp for Section_10

            Sample n_cells  cellranger reads raw  cellbender reads filt  percent filtered     Section Section_indiv  no_reads_removed
0  WS_wEMB12142141   10165           133212913.0            132660803.0             0.410  Section_10  Section_10_a          552110.0
1  WS_wEMB12142145    9777           115073138.0            114845662.0             0.200  Section_10  Section_10_b          227476.0
2  WS_wEMB12142149   10637           120137049.0            119837797.0             0.250  Section_10  Section_10_c          299252.0
3  WS_wEMB12142153    9616           102982066.0            102654291.0             0.320  Section_10  Section_10_d          327775.0
4         Combined   40195           471405166.0            469998553.0             0.295  Section_10           all         1406613.0



Embryo3_outs_comp for Section_11

            Sample n_cells  cellranger reads raw  cellbender reads filt  percent filtered     Section Section_indiv  no_reads_removed
0  WS_wEMB12142142    6305            54277130.0             54023264.0            0.4700  Section_11  Section_11_a          253866.0
1  WS_wEMB12142146   10003           106404266.0            106036265.0            0.3500  Section_11  Section_11_b          368001.0
2  WS_wEMB12142150    8931           100812652.0            100229730.0            0.5800  Section_11  Section_11_c          582922.0
3  WS_wEMB12142154    8807           108174566.0            107705635.0            0.4300  Section_11  Section_11_d          468931.0
4         Combined   34046           369668614.0            367994894.0            0.4575  Section_11           all         1673720.0



Embryo3_outs_comp for Section_12

            Sample n_cells  cellranger reads raw  cellbender reads filt  percent filtered     Section Section_indiv  no_reads_removed
0  WS_wEMB12142143   10669           100005950.0             99579444.0             0.430  Section_12  Section_12_a          426506.0
1  WS_wEMB12142147   11423           152773167.0            151945159.0             0.540  Section_12  Section_12_b          828008.0
2  WS_wEMB12142151   10878            97507505.0             96967520.0             0.550  Section_12  Section_12_c          539985.0
3  WS_wEMB12142155   11124           119229762.0            118637396.0             0.500  Section_12  Section_12_d          592366.0
4         Combined   44094           469516384.0            467129519.0             0.505  Section_12           all         2386865.0

***
### Dependencies
Here are some information about resources and import package versions used within this script

In [1]:
%load_ext watermark
%watermark -v -m -p numpy,pandas,scanpy,anndata

Python implementation: CPython
Python version       : 3.9.4
IPython version      : 7.24.1

numpy  : 1.20.3
pandas : 1.2.4
scanpy : 1.7.2
anndata: 0.7.6

Compiler    : GCC 9.3.0
OS          : Linux
Release     : 4.15.0-112-generic
Machine     : x86_64
Processor   : x86_64
CPU cores   : 26
Architecture: 64bit